-- ============================================================
--  Filey ERP — SMS/OTP/Template + CRM/ERP customization schema
--  Run in:  Supabase Dashboard → SQL Editor → New query
--  Safe to re-run (idempotent — uses if not exists).
--  Applied: 2026-06-16
-- ============================================================

-- 1. Default unit of measure for products so invoices can auto-fill unit.
alter table products add column if not exists unit text;

-- 2. SMS provider configurations (Twilio, etc.)
create table if not exists sms_providers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  org_id text not null,
  name text not null default 'Twilio',
  provider_type text not null default 'twilio',
  credentials jsonb not null default '{}',
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  shared boolean not null default false
);

-- 3. User-defined SMS / message templates with variable placeholders e.g. {{name}}
create table if not exists sms_templates (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  org_id text not null,
  name text not null,
  body text not null,
  variables text[] not null default '{}',
  category text not null default 'general',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  shared boolean not null default false
);

-- 4. SMS send log
CREATE TABLE IF NOT EXISTS sms_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  org_id text not null,
  provider_id bigint references sms_providers(id) on delete set null,
  template_id bigint references sms_templates(id) on delete set null,
  "to" text not null,
  body text not null,
  status text not null default 'pending',
  external_id text,
  error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  shared boolean not null default false
);

-- 5. OTP verification codes
CREATE TABLE IF NOT EXISTS otp_codes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  org_id text not null,
  target text not null,
  code text not null,
  purpose text not null default 'login',
  attempts int not null default 0,
  max_attempts int not null default 5,
  expires_at timestamptz not null,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  shared boolean not null default false
);

-- 6. Custom fields schema for CRM/ERP entities
CREATE TABLE IF NOT EXISTS custom_entity_fields (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  org_id text not null,
  entity_type text not null,
  field_key text not null,
  field_label text not null,
  field_type text not null default 'text',
  options jsonb,
  is_required boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  shared boolean not null default false,
  unique(org_id, entity_type, field_key)
);

-- 7. Custom field values per entity record
CREATE TABLE IF NOT EXISTS custom_entity_values (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  org_id text not null,
  entity_type text not null,
  entity_id bigint not null,
  field_key text not null,
  value text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  shared boolean not null default false,
  unique(org_id, entity_type, entity_id, field_key)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sms_providers_org ON sms_providers(org_id);
CREATE INDEX IF NOT EXISTS idx_sms_templates_org ON sms_templates(org_id);
CREATE INDEX IF NOT EXISTS idx_sms_logs_org ON sms_logs(org_id);
CREATE INDEX IF NOT EXISTS idx_sms_logs_created ON sms_logs(created_at desc);
CREATE INDEX IF NOT EXISTS idx_otp_codes_target ON otp_codes(target);
CREATE INDEX IF NOT EXISTS idx_otp_codes_expires ON otp_codes(expires_at);
CREATE INDEX IF NOT EXISTS idx_custom_fields_entity ON custom_entity_fields(org_id, entity_type);
CREATE INDEX IF NOT EXISTS idx_custom_values_entity ON custom_entity_values(org_id, entity_type, entity_id);

-- Enable RLS
ALTER TABLE sms_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE otp_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_entity_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_entity_values ENABLE ROW LEVEL SECURITY;

-- RLS: users see only rows in their current org.
-- Helper for org membership (already present from schema.sql usually, but safe to create).
create or replace function current_org_id() returns text as $$
  select current_setting('app.current_org_id', true);
$$ language sql stable;

drop policy if exists "org_isolation" on sms_providers;
create policy "org_isolation" on sms_providers
  for all to authenticated
  using (org_id = current_org_id())
  with check (org_id = current_org_id());

drop policy if exists "org_isolation" on sms_templates;
create policy "org_isolation" on sms_templates
  for all to authenticated
  using (org_id = current_org_id())
  with check (org_id = current_org_id());

drop policy if exists "org_isolation" on sms_logs;
create policy "org_isolation" on sms_logs
  for all to authenticated
  using (org_id = current_org_id())
  with check (org_id = current_org_id());

drop policy if exists "org_isolation" on otp_codes;
create policy "org_isolation" on otp_codes
  for all to authenticated
  using (org_id = current_org_id())
  with check (org_id = current_org_id());

drop policy if exists "org_isolation" on custom_entity_fields;
create policy "org_isolation" on custom_entity_fields
  for all to authenticated
  using (org_id = current_org_id())
  with check (org_id = current_org_id());

drop policy if exists "org_isolation" on custom_entity_values;
create policy "org_isolation" on custom_entity_values
  for all to authenticated
  using (org_id = current_org_id())
  with check (org_id = current_org_id());

-- Trigger: set updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

drop trigger if exists set_updated_at on sms_providers;
create trigger set_updated_at before update on sms_providers
  for each row execute procedure set_updated_at();

drop trigger if exists set_updated_at on sms_templates;
create trigger set_updated_at before update on sms_templates
  for each row execute procedure set_updated_at();

drop trigger if exists set_updated_at on custom_entity_fields;
create trigger set_updated_at before update on custom_entity_fields
  for each row execute procedure set_updated_at();

drop trigger if exists set_updated_at on custom_entity_values;
create trigger set_updated_at before update on custom_entity_values
  for each row execute procedure set_updated_at();
