-- Team comms: channels for chat, a log of email actually sent, and call records.
--
-- Chat already existed (org_messages, with parent_id threading) but as a single
-- global feed, and the component was never mounted anywhere. Channels turn it
-- into something a team can actually use without every topic colliding.
--
-- Email was send-only with no record kept: Filey could email an invoice and
-- then had no idea it ever had. email_messages is that record, so a customer's
-- page can show what was sent to them. It is NOT an inbox — receiving mail
-- needs inbound MX/webhooks that this project does not have.
--
-- Calls are logged, not carried: a real call needs signalling and TURN
-- servers. What an ERP actually needs is the record — who spoke to whom, when,
-- what was agreed — which is what this stores.

-- ---------- chat channels ----------
-- Plain text, defaulted, so every existing message lands in #general instead
-- of disappearing from a filtered view.
alter table public.org_messages
  add column if not exists channel text not null default 'general';

create index if not exists org_messages_channel_idx
  on public.org_messages (org_id, channel, id desc);

-- The channel roster. Kept as rows rather than inferred from messages so an
-- empty channel still exists and can be posted into.
create table if not exists public.org_channels (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name        text not null,
  purpose     text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------- email log ----------
create table if not exists public.email_messages (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  to_email      text not null,
  to_name       text,
  subject       text not null default '',
  body          text,
  -- What this was about, so a customer page can show its own correspondence.
  -- Deliberately the same vocabulary as entity_links.
  entity_type   text,
  entity_id     bigint,
  status        text not null default 'sent',   -- sent | failed
  error         text,
  sent_at       timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists email_messages_entity_idx
  on public.email_messages (entity_type, entity_id);
create index if not exists email_messages_to_idx
  on public.email_messages (to_email);
create index if not exists email_messages_sent_idx
  on public.email_messages (sent_at desc);

-- ---------- call log ----------
create table if not exists public.call_logs (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  direction     text not null default 'outgoing',  -- outgoing | incoming | missed
  contact_name  text,
  contact_phone text,
  entity_type   text,
  entity_id     bigint,
  started_at    timestamptz not null default now(),
  duration_secs integer not null default 0,
  outcome       text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists call_logs_entity_idx
  on public.call_logs (entity_type, entity_id);
create index if not exists call_logs_started_idx
  on public.call_logs (started_at desc);

-- ---------- org scoping + RLS for the three new tables ----------
-- Same shape every other business table gets from the loop in schema.sql:
-- org_id pinned by trigger, RLS on, own-rows-or-shared-within-org. Written out
-- here so applying this file alone never leaves a table world-readable.
do $$
declare
  t text;
  tables text[] := array['org_channels','email_messages','call_logs'];
begin
  foreach t in array tables loop
    execute format(
      'alter table public.%I add column if not exists org_id text not null default public.current_org();', t);
    execute format(
      'alter table public.%I add column if not exists shared boolean not null default false;', t);
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop trigger if exists %I on public.%I;', 'trg_'||t||'_updated', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function set_updated_at();',
      'trg_'||t||'_updated', t);

    -- SECURITY: pins org_id on insert, freezes it on update — no cross-tenant
    -- rows can be injected into a team's channels or call history.
    execute format('drop trigger if exists %I on public.%I;', 'trg_'||t||'_org', t);
    execute format(
      'create trigger %I before insert or update on public.%I for each row execute function public.force_org_id();',
      'trg_'||t||'_org', t);

    execute format('drop policy if exists %I on public.%I;', t||'_access', t);
    execute format(
      'create policy %I on public.%I for all '
      || 'using (user_id = (select auth.uid()) '
      || 'or (org_id = (select public.current_org()) '
      || 'and ((select public.is_org_admin()) or shared = true))) '
      || 'with check (user_id = (select auth.uid()) '
      || 'or (org_id = (select public.current_org()) and (select public.is_org_admin())));',
      t||'_access', t);
  end loop;
end $$;

-- Channels are a team roster, not private notes: a channel one member creates
-- has to be visible to the rest, which is what shared = true means here.
alter table public.org_channels alter column shared set default true;

-- No seed row here: user_id defaults to auth.uid(), which is null when this
-- file is applied from an admin/SQL context, so the insert would fail. The app
-- creates #general on first use instead, where a real user owns it.
