-- ============================================================
--  Filey ERP — stock_movements: one row per stock quantity change
--  Run in:  Supabase Dashboard → SQL Editor → New query
--  Safe to re-run (idempotent).
--  NOTE: local/offline mode (localdb.ts) is schemaless — no change needed
--  there; movement rows flow through the sb() shim automatically.
--  The legacy `stock_issues` JSON app-setting is migrated lazily by the app
--  on first read (api.ts migrateLegacyStockIssues) — no SQL backfill here.
-- ============================================================

create table if not exists stock_movements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  product_id bigint references products(id) on delete cascade,
  qty numeric(14,3) not null,           -- signed: positive = in, negative = out
  type text not null default 'adjust',  -- 'sale'|'purchase'|'order'|'in'|'out'|'adjust'
  ref text,
  note text,
  moved_at timestamptz not null default now(),
  shared boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stock_movements_product on stock_movements(product_id);
create index if not exists idx_stock_movements_moved on stock_movements(moved_at);

-- Same RLS / org-scoping / triggers as every other per-member table
-- (mirrors the schema.sql do-block for one table).
alter table stock_movements add column if not exists org_id text not null default public.current_org();
alter table stock_movements enable row level security;

drop trigger if exists trg_stock_movements_updated on stock_movements;
create trigger trg_stock_movements_updated before update on stock_movements
  for each row execute function set_updated_at();

drop trigger if exists trg_stock_movements_org on stock_movements;
create trigger trg_stock_movements_org before insert or update on stock_movements
  for each row execute function public.force_org_id();

drop policy if exists stock_movements_owner on stock_movements;
drop policy if exists stock_movements_org on stock_movements;
drop policy if exists stock_movements_access on stock_movements;
create policy stock_movements_access on stock_movements for all
  using (user_id = auth.uid()
    or (org_id = public.current_org()
      and (public.is_org_admin() or shared = true)))
  with check (user_id = auth.uid()
    or (org_id = public.current_org() and public.is_org_admin()));

create index if not exists idx_stock_movements_org on stock_movements(org_id);
create index if not exists idx_stock_movements_user on stock_movements(user_id);

-- realtime feed (idempotent)
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'stock_movements'
  ) then
    alter publication supabase_realtime add table public.stock_movements;
  end if;
end $$;
