-- Marketing campaigns + the opt-out list that governs them.
--
-- Two tables, and the second one matters more than the first: `email_optouts`
-- is the record of who asked not to be contacted. Every campaign send checks it,
-- and nothing in the app deletes from it. Losing this table means mailing people
-- who told you to stop.
--
-- Safe to re-run.

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default '',
  subject text not null default '',
  body_html text not null default '',
  -- draft | sending | sent | paused
  status text not null default 'draft',
  -- How the recipient list was chosen, kept so a campaign can be explained later.
  audience jsonb not null default '{}'::jsonb,
  -- [{customer_id, name, email, status, error, sent_at}] — small by nature; a
  -- campaign is hundreds of rows, not millions.
  recipients jsonb not null default '[]'::jsonb,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_optouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  email text not null,
  -- 'unsubscribed' | 'bounced' | 'manual'
  reason text not null default 'unsubscribed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Org scoping + RLS, mirroring what schema.sql's loop does for every other
-- tenant table (org_id pinned on write by force_org_id(), rows visible to their
-- owner, to org admins, or when explicitly shared).
do $$
declare t text;
begin
  foreach t in array array['campaigns', 'email_optouts'] loop
    execute format(
      'alter table %I add column if not exists org_id text not null default public.current_org();',
      t
    );
    execute format(
      'alter table %I add column if not exists shared boolean not null default false;',
      t
    );
    execute format('alter table %I enable row level security;', t);

    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_updated', t);
    execute format(
      'create trigger %I before update on %I for each row execute function set_updated_at();',
      'trg_' || t || '_updated', t
    );
    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_org', t);
    execute format(
      'create trigger %I before insert or update on %I for each row execute function public.force_org_id();',
      'trg_' || t || '_org', t
    );

    execute format('drop policy if exists %I on %I;', t || '_access', t);
    execute format(
      'create policy %I on %I for all '
      || 'using (user_id = (select auth.uid()) '
      || 'or (org_id = (select public.current_org()) '
      || 'and ((select public.is_org_admin()) or shared = true))) '
      || 'with check (user_id = (select auth.uid()) '
      || 'or (org_id = (select public.current_org()) and (select public.is_org_admin())));',
      t || '_access', t
    );
  end loop;
end $$;

-- One opt-out per address per org. Case-insensitive: someone who unsubscribed as
-- Sales@Acme.ae must not be reachable again as sales@acme.ae.
create unique index if not exists idx_email_optouts_unique
  on public.email_optouts (org_id, lower(email));

create index if not exists idx_campaigns_org_status
  on public.campaigns (org_id, status);

comment on table public.email_optouts is
  'Addresses that must never receive a campaign. Checked on every send; append-only in practice.';
