-- "I want the Freedom plan" requests, from the website and from inside the app.
--
-- Stripe is not in the loop right now, so the paid plan is sold by conversation:
-- the button takes a name and a number and emails the owner. Those leads land
-- here as well as in the inbox, because an email is a notification and this is
-- the record — and because counting rows per IP is what throttles a public
-- endpoint without inventing a second table.
--
-- Nothing but the service role (the lead-contact function) may touch it: the
-- rows carry personal contact details and no signed-in user needs to read them.
--
-- Idempotent. Run once:
--   supabase db execute --file supabase/2026-08-13-lead-requests.sql
create table if not exists public.lead_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  message text,
  plan text not null default 'freedom',
  /** Where it came from: "website" | "app". */
  source text not null default 'website',
  /** Coarse origin, for throttling only. */
  ip text,
  emailed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_lead_requests_ip_time
  on public.lead_requests (ip, created_at desc);

alter table public.lead_requests enable row level security;
revoke all on public.lead_requests from anon, authenticated;
