-- 2026-07-26: CRM relational objects — people, notes, tasks, and real foreign
-- keys between deals and the records they belong to.
--
-- Idempotent: safe to re-run.
--
-- Why: the CRM linked records by TEXT. crm_opportunities pointed at a customer
-- through `customer_name`, crm_activities through `related_to`. Renaming a
-- company silently orphaned its deals, two customers with the same name were
-- indistinguishable, and nothing could be attached to a deal or a person at
-- all. Everything richer — pipelines, timelines, per-record activity — needs
-- real relations underneath, so this migration adds them.
--
-- Object model after this migration:
--
--   crm_customers (the COMPANY / account — unchanged, still what invoices,
--                  quotes and advances reference)
--        │
--        ├──< crm_people          contacts at that company
--        └──< crm_opportunities   deals, now via customer_id (+ person_id)
--
--   crm_notes / crm_tasks / crm_activities attach to ANY record through
--   (target_type, target_id): 'company' | 'person' | 'deal' | 'lead' | 'invoice'
--
-- Back-compat: the old TEXT columns are kept and still populated. Nothing that
-- reads customer_name or related_to breaks; new code prefers the id columns.

-- ---------- contacts ----------
create table if not exists crm_people (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  company_id bigint references crm_customers(id) on delete set null,
  name text not null default '',
  title text,
  email text,
  phone text,
  phone_e164 text,
  linkedin text,
  notes text,
  owner text,
  is_primary boolean not null default false,
  custom_fields jsonb default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- notes: free text attached to any record ----------
create table if not exists crm_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  target_type text not null,
  target_id bigint not null,
  body text not null default '',
  author text,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- tasks: assignable, due-dated work on any record ----------
create table if not exists crm_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  target_type text,
  target_id bigint,
  title text not null default '',
  body text,
  due_date date,
  -- open | in_progress | done | cancelled
  status text not null default 'open',
  priority text,
  assignee text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- deals: real relations, pipeline, outcome ----------
alter table crm_opportunities add column if not exists customer_id bigint references crm_customers(id) on delete set null;
alter table crm_opportunities add column if not exists person_id bigint references crm_people(id) on delete set null;
alter table crm_opportunities add column if not exists pipeline text not null default 'sales';
alter table crm_opportunities add column if not exists close_reason text;
alter table crm_opportunities add column if not exists closed_at timestamptz;

-- ---------- activities: attach to any record, not just a name ----------
alter table crm_activities add column if not exists target_type text;
alter table crm_activities add column if not exists target_id bigint;

-- ---------- indexes ----------
create index if not exists crm_people_company_idx on crm_people (company_id);
create index if not exists crm_notes_target_idx on crm_notes (target_type, target_id, created_at desc);
create index if not exists crm_tasks_target_idx on crm_tasks (target_type, target_id);
create index if not exists crm_tasks_open_idx on crm_tasks (status, due_date);
create index if not exists crm_opportunities_customer_idx on crm_opportunities (customer_id);
create index if not exists crm_activities_target_idx on crm_activities (target_type, target_id);

-- ---------- RLS + org scoping + updated_at, matching schema.sql ----------
-- Same privacy model as every other app table: a member's rows are private to
-- them, org owners/admins see everything in the org, and `shared = true` opts a
-- row into org-wide read. force_org_id() pins org_id on insert and freezes it
-- on update so rows can't be moved between tenants.
do $$
declare
  t text;
  tables text[] := array['crm_people', 'crm_notes', 'crm_tasks'];
begin
  foreach t in array tables loop
    execute format(
      'alter table %I add column if not exists org_id text not null default public.current_org();',
      t
    );
    execute format('alter table %I enable row level security;', t);

    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_updated', t);
    execute format(
      'create trigger %I before update on %I for each row execute function set_updated_at();',
      'trg_' || t || '_updated', t
    );

    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_org', t);
    execute format(
      'create trigger %I before insert or update on %I for each row execute function public.force_org_id();',
      'trg_' || t || '_org', t
    );

    execute format(
      'alter table %I add column if not exists shared boolean not null default false;',
      t
    );

    execute format('drop policy if exists %I on %I;', t || '_access', t);
    execute format(
      'create policy %I on %I for all '
      || 'using (user_id = auth.uid() '
      || 'or (org_id = public.current_org() '
      || 'and (public.is_org_admin() or shared = true))) '
      || 'with check (user_id = auth.uid() '
      || 'or (org_id = public.current_org() and public.is_org_admin()));',
      t || '_access', t
    );
  end loop;
end $$;

-- ---------- backfill: link existing deals to their company ----------
-- Deals stored only a display name, which was set to `company || name` at
-- creation. Match on either, within the same org, and only when exactly one
-- customer matches — an ambiguous name is left null rather than mislinked.
update crm_opportunities o
set customer_id = c.id
from crm_customers c
where o.customer_id is null
  and o.org_id = c.org_id
  and btrim(lower(o.customer_name)) in (btrim(lower(c.company)), btrim(lower(c.name)))
  and (
    select count(*) from crm_customers c2
    where c2.org_id = o.org_id
      and btrim(lower(o.customer_name)) in (btrim(lower(c2.company)), btrim(lower(c2.name)))
  ) = 1;

-- ---------- backfill: a contact for every customer that named a person ----------
-- crm_customers merged company and contact on one row: `company` held the
-- business, `name` the human. Where those differ, promote the human to a real
-- contact row. Skipped when a person with that name already exists.
insert into crm_people (user_id, org_id, company_id, name, email, phone, phone_e164, is_primary)
select c.user_id, c.org_id, c.id, c.name, c.email, c.phone, c.phone_e164, true
from crm_customers c
where coalesce(btrim(c.name), '') <> ''
  and coalesce(btrim(c.company), '') <> ''
  and btrim(lower(c.name)) <> btrim(lower(c.company))
  and not exists (
    select 1 from crm_people p
    where p.company_id = c.id and btrim(lower(p.name)) = btrim(lower(c.name))
  );
