-- Entity links: connect any record to any other record.
--
-- Filey has the objects already — invoices, quotations, purchase orders,
-- customers, suppliers, products, follow-ups, receipts, expenses — but nothing
-- joins them. The only existing cross-reference is crm_activities.related_to,
-- which stores a *name* ("Acme Trading"), so renaming a customer silently
-- orphans its history.
--
-- One generic edge table fixes that for every pair at once, instead of adding
-- a foreign key per combination. An edge is (from_type,from_id) → (to_type,to_id)
-- plus a kind, and it is read in BOTH directions: opening a purchase order
-- shows the invoice it produced, and opening that invoice shows the PO it came
-- from, without storing the edge twice.
--
-- Types are plain text on purpose. A CHECK constraint listing today's tables
-- would need a migration every time a module is added, and the app already
-- owns the vocabulary (see ENTITY_TYPES in src/lib/links.ts).

create table if not exists public.entity_links (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  from_type   text not null,
  from_id     bigint not null,
  to_type     text not null,
  to_id       bigint not null,
  -- Free-form label for the edge ("produced", "paid by", "mentions"). Kept
  -- loose: the point of the graph is that a link exists, not its taxonomy.
  kind        text not null default 'related',
  note        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- The same edge twice is noise, and re-linking is a common double-click.
create unique index if not exists entity_links_unique
  on public.entity_links (from_type, from_id, to_type, to_id, kind);

-- Both directions are hot: every record view asks "what points at me?" as well
-- as "what do I point at?".
create index if not exists entity_links_from_idx
  on public.entity_links (from_type, from_id);
create index if not exists entity_links_to_idx
  on public.entity_links (to_type, to_id);

-- org_id, RLS, the updated_at trigger and the force_org_id trigger all come
-- from the loop in schema.sql, which now lists entity_links. Applying this
-- file alone (on a database already carrying that loop) needs the same shape
-- reproduced here so the table is never left readable by the whole world.
alter table public.entity_links
  add column if not exists org_id text not null default public.current_org();
alter table public.entity_links
  add column if not exists shared boolean not null default false;
alter table public.entity_links enable row level security;

drop trigger if exists trg_entity_links_updated on public.entity_links;
create trigger trg_entity_links_updated
  before update on public.entity_links
  for each row execute function set_updated_at();

-- SECURITY: pins org_id on insert and freezes it on update, so an edge cannot
-- be injected into another tenant's graph.
drop trigger if exists trg_entity_links_org on public.entity_links;
create trigger trg_entity_links_org
  before insert or update on public.entity_links
  for each row execute function public.force_org_id();

-- Same clause the other business tables use: your own rows, or your org's when
-- shared / you are an org admin. The admin and shared branches stay scoped to
-- org_id so they cannot reach across tenants.
drop policy if exists entity_links_access on public.entity_links;
create policy entity_links_access
  on public.entity_links
  for all
  using (
    user_id = (select auth.uid())
    or (
      org_id = (select public.current_org())
      and ((select public.is_org_admin()) or shared = true)
    )
  )
  with check (
    user_id = (select auth.uid())
    or (
      org_id = (select public.current_org())
      and (select public.is_org_admin())
    )
  );
