-- Additive project delivery and support records. No existing table is changed.
begin;
create table if not exists public.work_items (
  id bigint generated by default as identity primary key,
  org_id text not null default public.current_org(),
  user_id uuid not null default auth.uid() references auth.users(id),
  kind text not null check (kind in ('project', 'ticket')),
  title text not null check (length(trim(title)) between 1 and 200),
  description text not null default '' check (length(description) <= 20000),
  status text not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  owner text not null default '' check (length(owner) <= 200),
  customer_id bigint references public.crm_customers(id) on delete set null,
  invoice_id bigint references public.invoice_docs(id) on delete set null,
  due_date date,
  budget_hours numeric not null default 0 check (budget_hours >= 0 and budget_hours <= 100000),
  checklist jsonb not null default '[]' check (jsonb_typeof(checklist) = 'array' and jsonb_array_length(checklist) <= 200),
  time_entries jsonb not null default '[]' check (jsonb_typeof(time_entries) = 'array' and jsonb_array_length(time_entries) <= 500),
  updates jsonb not null default '[]' check (jsonb_typeof(updates) = 'array' and jsonb_array_length(updates) <= 500),
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((kind = 'project' and status in ('planned', 'active', 'blocked', 'completed', 'archived'))
    or (kind = 'ticket' and status in ('open', 'in_progress', 'waiting', 'resolved', 'closed', 'archived')))
);
alter table public.work_items enable row level security;
drop policy if exists work_items_own on public.work_items;
create policy work_items_own on public.work_items for all to authenticated
  using (user_id = (select auth.uid()) and org_id = (select public.current_org()))
  with check (user_id = (select auth.uid()) and org_id = (select public.current_org()));
grant select, insert, update, delete on public.work_items to authenticated;
grant usage, select on sequence public.work_items_id_seq to authenticated;
drop trigger if exists work_items_org on public.work_items;
create trigger work_items_org before insert or update on public.work_items for each row execute function public.force_org_id();

-- Invoker queries retain the caller's RLS when resolving references.
create or replace function public.validate_work_item() returns trigger
language plpgsql security invoker set search_path = public, pg_temp as $$
begin
  if TG_OP = 'UPDATE' then
    if new.kind <> old.kind or new.user_id <> old.user_id then raise exception 'Record kind and account owner cannot change'; end if;
    new.revision := old.revision + 1;
  end if;
  new.updated_at := now();
  if new.customer_id is not null and not exists (select 1 from public.crm_customers where id = new.customer_id and org_id = new.org_id) then raise exception 'Customer is not available in this workspace'; end if;
  if new.invoice_id is not null and not exists (select 1 from public.invoice_docs where id = new.invoice_id and org_id = new.org_id) then raise exception 'Invoice is not available in this workspace'; end if;
  return new;
end;
$$;
drop trigger if exists work_items_validate on public.work_items;
create trigger work_items_validate before insert or update on public.work_items for each row execute function public.validate_work_item();
create index if not exists work_items_owner_kind on public.work_items(user_id, org_id, kind, status, due_date);
do $$ begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'work_items') then
    alter publication supabase_realtime add table public.work_items;
  end if;
end $$;
notify pgrst, 'reload schema';
commit;
