-- Follow-ups / reminders. Personal to each user (their own reminders),
-- optionally linked to a customer. The app surfaces due/overdue items as
-- in-app reminders. Idempotent. Run once:
--   supabase db execute --file supabase/follow-ups.sql
create table if not exists public.follow_ups (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  org_id text not null default public.current_org(),
  customer_id bigint references public.crm_customers(id) on delete set null,
  customer_name text not null default '',
  title text not null,
  due_date date not null,
  done boolean not null default false,
  repeat text not null default 'none',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- A follow-up hangs off a customer or a supplier, never both. supplier_id is
-- the discriminator the Follow-ups page splits its two sections on: null means
-- the customer side (which is also where unlinked, general reminders live).
-- customer_name doubles as the supplier's display name — one label column for
-- whichever party the row points at.
alter table public.follow_ups
  add column if not exists supplier_id bigint
  references public.suppliers(id) on delete set null;

alter table public.follow_ups enable row level security;

drop policy if exists follow_ups_own on public.follow_ups;
create policy follow_ups_own on public.follow_ups for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create index if not exists idx_follow_ups_user_due
  on public.follow_ups (user_id, done, due_date);

-- live updates to open sessions
do $$
begin
  begin
    alter publication supabase_realtime add table public.follow_ups;
  exception when others then null;
  end;
end $$;
