-- Add unit column to purchase_order_items
alter table if exists public.purchase_order_items
  add column if not exists unit text;

-- Create po_payments table for tracking supplier payments
create table if not exists public.po_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  po_id bigint not null references public.purchase_orders(id) on delete cascade,
  amount numeric(14,2) not null default 0,
  method text,
  paid_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Index for fast lookups
create index if not exists idx_po_payments_po on public.po_payments (po_id);
