-- Recurring invoices (#17). Mirrors the standard owner-or-org RLS used by the
-- other per-user tables. A recurrence points at a base invoice that gets
-- cloned each period. Additive + idempotent.

create table if not exists invoice_recurrence (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  org_id text not null default public.current_org(),
  base_invoice_id bigint not null references invoice_docs(id) on delete cascade,
  interval text not null default 'monthly',   -- weekly | monthly | yearly
  next_run date not null,
  last_run date,
  active boolean not null default true,
  shared boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table invoice_recurrence enable row level security;

drop trigger if exists trg_invoice_recurrence_updated on invoice_recurrence;
create trigger trg_invoice_recurrence_updated before update on invoice_recurrence
  for each row execute function set_updated_at();

drop policy if exists invoice_recurrence_access on invoice_recurrence;
create policy invoice_recurrence_access on invoice_recurrence for all
  using (
    user_id = auth.uid()
    or (org_id = public.current_org() and (public.is_org_admin() or shared = true))
  )
  with check (
    user_id = auth.uid()
    or (org_id = public.current_org() and public.is_org_admin())
  );
