-- ============================================================
--  Filey ERP & CRM — Supabase schema
--  Run this once in:  Supabase Dashboard → SQL Editor → New query
--  Safe to re-run (idempotent).
-- ============================================================

-- ---------- PROFILES (one row per auth user) ----------
create table if not exists profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  org_id      text not null default 'default',
  email       text not null default '',
  name        text not null default 'User',
  company     text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Extra profile fields (additive, safe on existing projects)
alter table profiles add column if not exists phone text;
alter table profiles add column if not exists role text default 'Administrator';
alter table profiles add column if not exists username text;
alter table profiles add column if not exists avatar text;
alter table profiles add column if not exists language text default 'English (US)';
alter table profiles add column if not exists timezone text;
alter table profiles add column if not exists date_format text;
alter table profiles add column if not exists time_format text;

alter table profiles enable row level security;
drop policy if exists profiles_owner on profiles;
create policy profiles_owner on profiles
  for all using (id = auth.uid()) with check (id = auth.uid());

-- ---------- shared updated_at trigger fn ----------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_profiles_updated on profiles;
create trigger trg_profiles_updated before update on profiles
  for each row execute function set_updated_at();

-- ---------- business tables ----------
-- Numeric ids (bigint identity) keep the desktop app's TypeScript unchanged.
-- Every row is owned by the inserting user via user_id default auth.uid().

-- ===== ERP =====
create table if not exists products (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  sku text not null default '',
  name text not null default '',
  description text,
  category text,
  unit_price numeric(14,2) not null default 0,
  cost_price numeric(14,2) not null default 0,
  quantity bigint not null default 0,
  reorder_level bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  order_number text not null default '',
  customer_name text not null default '',
  status text not null default 'draft',
  total numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint,
  quantity bigint not null default 1,
  unit_price numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists invoices (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  invoice_number text not null default '',
  order_id bigint,
  customer_name text not null default '',
  amount numeric(14,2) not null default 0,
  status text not null default 'unpaid',
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== HR =====
create table if not exists employees (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  employee_code text not null default '',
  name text not null default '',
  email text,
  phone text,
  department text,
  position text,
  salary numeric(14,2) not null default 0,
  hire_date date,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  employee_id bigint references employees(id) on delete cascade,
  date date not null default current_date,
  check_in text,
  check_out text,
  status text not null default 'present',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists payroll (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  employee_id bigint references employees(id) on delete cascade,
  period text not null default '',
  basic numeric(14,2) not null default 0,
  allowances numeric(14,2) not null default 0,
  deductions numeric(14,2) not null default 0,
  net_pay numeric(14,2) not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== FINANCE =====
create table if not exists accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  code text not null default '',
  name text not null default '',
  account_type text not null default 'asset',
  balance numeric(16,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  category text not null default '',
  description text,
  amount numeric(14,2) not null default 0,
  expense_date date not null default current_date,
  account_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  account_id bigint,
  txn_type text not null default 'debit',
  amount numeric(16,2) not null default 0,
  description text,
  txn_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== TOOLS =====
create table if not exists app_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  username text not null default '',
  full_name text not null default '',
  role text not null default 'staff',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key text not null default '',
  value text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, key)
);

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  actor text not null default '',
  action text not null default '',
  entity text not null default '',
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== CRM =====
create table if not exists crm_leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default '',
  company text,
  email text,
  phone text,
  source text,
  status text not null default 'new',
  est_value numeric(14,2) not null default 0,
  owner text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists crm_customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default '',
  company text,
  email text,
  phone text,
  address text,
  segment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists crm_opportunities (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null default '',
  customer_name text not null default '',
  stage text not null default 'qualification',
  value numeric(14,2) not null default 0,
  probability bigint not null default 20,
  owner text,
  expected_close date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists crm_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  kind text not null default 'task',
  subject text not null default '',
  related_to text,
  due_date date,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== BILLING / INVOICING =====
create table if not exists company_profile (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default '',
  address text,
  trn text,
  email text,
  phone text,
  logo text,
  default_accent text not null default '#0A0A0A',
  default_template text not null default 'minimal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

-- Extra company-profile fields (additive, safe on existing projects)
alter table company_profile add column if not exists business_type text;
alter table company_profile add column if not exists city text;
alter table company_profile add column if not exists zip text;
alter table company_profile add column if not exists vat_number text;
alter table company_profile add column if not exists tax_type text default 'VAT';
alter table company_profile add column if not exists website text;
alter table company_profile add column if not exists currency text default 'AED';
alter table company_profile add column if not exists default_tax_rate numeric(8,3) default 5;

create table if not exists invoice_docs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  number text not null default '',
  status text not null default 'draft',
  template text not null default 'minimal',
  accent text not null default '#0A0A0A',
  currency text not null default 'AED',
  seller_name text not null default '',
  seller_address text,
  seller_trn text,
  seller_email text,
  seller_phone text,
  logo text,
  customer_name text not null default '',
  customer_address text,
  customer_trn text,
  customer_email text,
  issue_date date,
  due_date date,
  notes text,
  terms text,
  tax_rate numeric(8,3) not null default 5,
  discount numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists invoice_doc_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  invoice_id bigint references invoice_docs(id) on delete cascade,
  description text not null default '',
  qty numeric(14,3) not null default 1,
  unit_price numeric(14,2) not null default 0,
  position bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== QUOTING =====
create table if not exists quotations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  number text not null default '',
  status text not null default 'draft',
  template text not null default 'clean',
  accent text not null default '#E0AE00',
  currency text not null default 'USD',
  quote_date date,
  valid_until date,
  sales_person text,
  customer_name text not null default '',
  customer_address text,
  customer_trn text,
  customer_email text,
  terms text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists quotation_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  quotation_id bigint references quotations(id) on delete cascade,
  product text not null default '',
  sku text,
  qty numeric(14,3) not null default 1,
  rate numeric(14,2) not null default 0,
  discount numeric(8,3) not null default 0,
  tax numeric(8,3) not null default 0,
  position bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists quotation_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default '',
  base_template text not null default 'clean',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ===== TOOLS activity =====
create table if not exists tool_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  tool text not null default '',
  tool_name text not null default '',
  file_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- MULTI-TENANCY (organizations + members + RBAC) ----------
create extension if not exists pgcrypto;

create table if not exists organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'My Organization',
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists org_members (
  id bigint generated by default as identity primary key,
  org_id text not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  role text not null default 'staff',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, user_id)
);

-- Caller's active organization key (text). Defaults to 'default' so any
-- pre-existing single-user data keeps working unchanged after migration.
create or replace function public.current_org()
returns text language sql stable security definer set search_path = public as $$
  select coalesce(
    (select org_id from public.profiles where id = auth.uid()),
    'default'
  )
$$;

-- True when the caller is an owner/admin of their active org.
-- security definer avoids RLS recursion on org_members.
create or replace function public.is_org_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.org_members
    where org_id = public.current_org()
      and user_id = auth.uid()
      and role in ('owner', 'admin')
  )
$$;

alter table organizations enable row level security;
drop policy if exists organizations_access on organizations;
create policy organizations_access on organizations for all
  using (id::text = public.current_org() or owner_id = auth.uid())
  with check (owner_id = auth.uid());
drop trigger if exists trg_organizations_updated on organizations;
create trigger trg_organizations_updated before update on organizations
  for each row execute function set_updated_at();

alter table org_members enable row level security;
drop policy if exists org_members_select on org_members;
create policy org_members_select on org_members for select
  using (org_id = public.current_org() or user_id = auth.uid());
drop policy if exists org_members_self on org_members;
create policy org_members_self on org_members for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists org_members_admin on org_members;
create policy org_members_admin on org_members for all
  using (org_id = public.current_org() and public.is_org_admin())
  with check (org_id = public.current_org() and public.is_org_admin());
drop trigger if exists trg_org_members_updated on org_members;
create trigger trg_org_members_updated before update on org_members
  for each row execute function set_updated_at();

-- Team members may read each other's profiles within the same org.
drop policy if exists profiles_org_read on profiles;
create policy profiles_org_read on profiles for select
  using (org_id = public.current_org());

-- ---------- RLS + org scoping + updated_at trigger for every table ----------
do $$
declare
  t text;
  tables text[] := array[
    'products','orders','order_items','invoices',
    'employees','attendance','payroll',
    'accounts','expenses','transactions',
    'app_users','app_settings','audit_log',
    'crm_leads','crm_customers','crm_opportunities','crm_activities',
    'company_profile','invoice_docs','invoice_doc_items',
    'quotations','quotation_items','quotation_templates','tool_runs'
  ];
begin
  foreach t in array tables loop
    execute format(
      'alter table %I add column if not exists org_id text not null default public.current_org();',
      t
    );
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists %I on %I;', t || '_owner', t);
    execute format('drop policy if exists %I on %I;', t || '_org', t);
    execute format(
      'create policy %I on %I for all using (org_id = public.current_org()) with check (org_id = public.current_org());',
      t || '_org', t
    );
    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_updated', t);
    execute format(
      'create trigger %I before update on %I for each row execute function set_updated_at();',
      'trg_' || t || '_updated', t
    );
  end loop;
end $$;

-- ---------- auto-provision a personal org + profile on signup ----------
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  new_org uuid;
begin
  insert into public.organizations (id, name, owner_id)
  values (gen_random_uuid(), coalesce(new.email, 'My Organization'), new.id)
  returning id into new_org;

  insert into public.profiles (id, email, name, org_id)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', 'User'),
    new_org::text
  )
  on conflict (id) do nothing;

  insert into public.org_members (org_id, user_id, role)
  values (new_org::text, new.id, 'owner')
  on conflict (org_id, user_id) do nothing;

  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- Done. Tables are row-level-secured to the signed-in user.
