1|-- ============================================================
2|--  Filey ERP & CRM — Supabase schema
3|--  Run this once in:  Supabase Dashboard → SQL Editor → New query
4|--  Safe to re-run (idempotent).
5|-- ============================================================
6|
7|-- ---------- PROFILES (one row per auth user) ----------
8|create table if not exists profiles (
9|  id          uuid primary key references auth.users(id) on delete cascade,
10|  org_id      text not null default 'default',
11|  email       text not null default '',
12|  name        text not null default 'User',
13|  company     text not null default '',
14|  created_at  timestamptz not null default now(),
15|  updated_at  timestamptz not null default now()
16|);
17|
18|-- Extra profile fields (additive, safe on existing projects)
19|alter table profiles add column if not exists phone text;
20|alter table profiles add column if not exists role text default 'Administrator';
21|alter table profiles add column if not exists username text;
22|alter table profiles add column if not exists avatar text;
23|alter table profiles add column if not exists language text default 'English (US)';
24|alter table profiles add column if not exists timezone text;
25|alter table profiles add column if not exists date_format text;
26|alter table profiles add column if not exists time_format text;
27|
28|alter table profiles enable row level security;
29|-- SECURITY: a user may read/insert/delete only their own profile, and may
30|-- only switch their active org_id to an organization they actually belong
31|-- to. The old "for all" policy let a user set org_id to ANY org, which made
32|-- current_org() return that org and exposed its shared data.
33|drop policy if exists profiles_owner on profiles;
34|drop policy if exists profiles_self_select on profiles;
35|drop policy if exists profiles_self_insert on profiles;
36|drop policy if exists profiles_self_update on profiles;
37|drop policy if exists profiles_self_delete on profiles;
38|
39|create policy profiles_self_select on profiles for select
40|  using (id = auth.uid());
41|create policy profiles_self_insert on profiles for insert
42|  with check (id = auth.uid());
43|create policy profiles_self_update on profiles for update
44|  using (id = auth.uid())
45|  with check (
46|    id = auth.uid()
47|    and (
48|      org_id = 'default'
49|      or exists (
50|        select 1 from public.org_members m
51|        where m.org_id = profiles.org_id and m.user_id = auth.uid()
52|      )
53|    )
54|  );
55|create policy profiles_self_delete on profiles for delete
56|  using (id = auth.uid());
57|
58|-- ---------- shared updated_at trigger fn ----------
59|create or replace function set_updated_at()
60|returns trigger language plpgsql as $$
61|begin
62|  new.updated_at = now();
63|  return new;
64|end $$;
65|
66|drop trigger if exists trg_profiles_updated on profiles;
67|create trigger trg_profiles_updated before update on profiles
68|  for each row execute function set_updated_at();
69|
70|-- ---------- business tables ----------
71|-- Numeric ids (bigint identity) keep the desktop app's TypeScript unchanged.
72|-- Every row is owned by the inserting user via user_id default auth.uid().
73|
74|-- ===== ERP =====
75|create table if not exists products (
76|  id bigint generated by default as identity primary key,
77|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
78|  sku text not null default '',
79|  name text not null default '',
80|  description text,
81|  category text,
82|  unit_price numeric(14,2) not null default 0,
83|  cost_price numeric(14,2) not null default 0,
84|  quantity bigint not null default 0,
85|  reorder_level bigint not null default 0,
86|  created_at timestamptz not null default now(),
87|  updated_at timestamptz not null default now()
88|);
89|
90|create table if not exists orders (
91|  id bigint generated by default as identity primary key,
92|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
93|  order_number text not null default '',
94|  customer_name text not null default '',
95|  status text not null default 'draft',
96|  total numeric(14,2) not null default 0,
97|  created_at timestamptz not null default now(),
98|  updated_at timestamptz not null default now()
99|);
100|
101|create table if not exists order_items (
102|  id bigint generated by default as identity primary key,
103|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
104|  order_id bigint references orders(id) on delete cascade,
105|  product_id bigint,
106|  quantity bigint not null default 1,
107|  unit_price numeric(14,2) not null default 0,
108|  created_at timestamptz not null default now(),
109|  updated_at timestamptz not null default now()
110|);
111|
112|-- NOTE: the legacy `invoices` table was removed — billing now uses
113|-- `invoice_docs` exclusively. Drop it if it lingers from an old deploy.
114|drop table if exists public.invoices cascade;
115|
116|-- ===== HR =====
117|create table if not exists employees (
118|  id bigint generated by default as identity primary key,
119|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
120|  employee_code text not null default '',
121|  name text not null default '',
122|  email text,
123|  phone text,
124|  department text,
125|  position text,
126|  salary numeric(14,2) not null default 0,
127|  hire_date date,
128|  status text not null default 'active',
129|  created_at timestamptz not null default now(),
130|  updated_at timestamptz not null default now()
131|);
132|
133|create table if not exists attendance (
134|  id bigint generated by default as identity primary key,
135|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
136|  employee_id bigint references employees(id) on delete cascade,
137|  date date not null default current_date,
138|  check_in text,
139|  check_out text,
140|  status text not null default 'present',
141|  created_at timestamptz not null default now(),
142|  updated_at timestamptz not null default now()
143|);
144|
145|create table if not exists payroll (
146|  id bigint generated by default as identity primary key,
147|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
148|  employee_id bigint references employees(id) on delete cascade,
149|  period text not null default '',
150|  basic numeric(14,2) not null default 0,
151|  allowances numeric(14,2) not null default 0,
152|  deductions numeric(14,2) not null default 0,
153|  net_pay numeric(14,2) not null default 0,
154|  status text not null default 'pending',
155|  created_at timestamptz not null default now(),
156|  updated_at timestamptz not null default now()
157|);
158|
159|-- ===== FINANCE =====
160|create table if not exists accounts (
161|  id bigint generated by default as identity primary key,
162|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
163|  code text not null default '',
164|  name text not null default '',
165|  account_type text not null default 'asset',
166|  balance numeric(16,2) not null default 0,
167|  created_at timestamptz not null default now(),
168|  updated_at timestamptz not null default now()
169|);
170|
171|create table if not exists expenses (
172|  id bigint generated by default as identity primary key,
173|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
174|  category text not null default '',
175|  description text,
176|  amount numeric(14,2) not null default 0,
177|  expense_date date not null default current_date,
178|  account_id bigint,
179|  created_at timestamptz not null default now(),
180|  updated_at timestamptz not null default now()
181|);
182|
183|create table if not exists transactions (
184|  id bigint generated by default as identity primary key,
185|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
186|  account_id bigint,
187|  txn_type text not null default 'debit',
188|  amount numeric(16,2) not null default 0,
189|  description text,
190|  txn_date date not null default current_date,
191|  created_at timestamptz not null default now(),
192|  updated_at timestamptz not null default now()
193|);
194|
195|-- ===== SUPPLIERS / PURCHASE ORDERS =====
196|create table if not exists suppliers (
197|  id bigint generated by default as identity primary key,
198|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
199|  name text not null default '',
200|  contact_person text,
201|  email text,
202|  phone text,
203|  address text,
204|  tax_id text,
205|  notes text,
206|  created_at timestamptz not null default now(),
207|  updated_at timestamptz not null default now()
208|);
209|
210|alter table products add column if not exists supplier_id bigint references suppliers(id) on delete set null;
211|alter table products add column if not exists batch_number  text;
212|alter table products add column if not exists expiry_date   date;
213|alter table products add column if not exists barcode       text;
214|alter table products add column if not exists warehouse     text;
215|alter table products add column if not exists is_serialized boolean not null default false;
216|alter table products add column if not exists custom_fields jsonb;
217|
218|create table if not exists purchase_orders (
219|  id bigint generated by default as identity primary key,
220|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
221|  po_number text not null default '',
222|  supplier_id bigint references suppliers(id) on delete set null,
223|  status text not null default 'draft',
224|  total numeric(14,2) not null default 0,
225|  order_date date not null default current_date,
226|  expected_date date,
227|  notes text,
228|  created_at timestamptz not null default now(),
229|  updated_at timestamptz not null default now()
230|);
231|
232|create table if not exists purchase_order_items (
233|  id bigint generated by default as identity primary key,
234|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
235|  po_id bigint references purchase_orders(id) on delete cascade,
236|  product_id bigint references products(id) on delete set null,
237|  description text not null default '',
238|  quantity numeric(14,3) not null default 1,
239|  unit_cost numeric(14,2) not null default 0,
240|  position bigint not null default 0,
241|  created_at timestamptz not null default now(),
242|  updated_at timestamptz not null default now()
243|);
244|
245|-- ===== TOOLS =====
246|create table if not exists app_users (
247|  id bigint generated by default as identity primary key,
248|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
249|  username text not null default '',
250|  full_name text not null default '',
251|  role text not null default 'staff',
252|  active boolean not null default true,
253|  created_at timestamptz not null default now(),
254|  updated_at timestamptz not null default now()
255|);
256|
257|create table if not exists app_settings (
258|  id bigint generated by default as identity primary key,
259|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
260|  key text not null default '',
261|  value text not null default '',
262|  created_at timestamptz not null default now(),
263|  updated_at timestamptz not null default now(),
264|  unique (user_id, key)
265|);
266|
267|create table if not exists audit_log (
268|  id bigint generated by default as identity primary key,
269|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
270|  actor text not null default '',
271|  action text not null default '',
272|  entity text not null default '',
273|  details text,
274|  created_at timestamptz not null default now(),
275|  updated_at timestamptz not null default now()
276|);
277|
278|-- ===== CRM =====
279|create table if not exists crm_leads (
280|  id bigint generated by default as identity primary key,
281|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
282|  name text not null default '',
283|  company text,
284|  email text,
285|  phone text,
286|  source text,
287|  status text not null default 'new',
288|  est_value numeric(14,2) not null default 0,
289|  owner text,
290|  created_at timestamptz not null default now(),
291|  updated_at timestamptz not null default now()
292|);
293|
294|create table if not exists crm_customers (
295|  id bigint generated by default as identity primary key,
296|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
297|  name text not null default '',
298|  company text,
299|  email text,
300|  phone text,
301|  address text,
302|  segment text,
303|  created_at timestamptz not null default now(),
304|  updated_at timestamptz not null default now()
305|);
306|
307|create table if not exists crm_opportunities (
308|  id bigint generated by default as identity primary key,
309|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
310|  title text not null default '',
311|  customer_name text not null default '',
312|  stage text not null default 'qualification',
313|  value numeric(14,2) not null default 0,
314|  probability bigint not null default 20,
315|  owner text,
316|  expected_close date,
317|  created_at timestamptz not null default now(),
318|  updated_at timestamptz not null default now()
319|);
320|
321|create table if not exists crm_activities (
322|  id bigint generated by default as identity primary key,
323|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
324|  kind text not null default 'task',
325|  subject text not null default '',
326|  related_to text,
327|  due_date date,
328|  done boolean not null default false,
329|  created_at timestamptz not null default now(),
330|  updated_at timestamptz not null default now()
331|);
332|
333|-- ===== BILLING / INVOICING =====
334|create table if not exists company_profile (
335|  id bigint generated by default as identity primary key,
336|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
337|  name text not null default '',
338|  address text,
339|  trn text,
340|  email text,
341|  phone text,
342|  logo text,
343|  default_accent text not null default '#0A0A0A',
344|  default_template text not null default 'minimal',
345|  created_at timestamptz not null default now(),
346|  updated_at timestamptz not null default now(),
347|  unique (user_id)
348|);
349|
350|-- Extra company-profile fields (additive, safe on existing projects)
351|alter table company_profile add column if not exists business_type text;
352|alter table company_profile add column if not exists city text;
353|alter table company_profile add column if not exists zip text;
354|alter table company_profile add column if not exists vat_number text;
355|alter table company_profile add column if not exists tax_type text default 'VAT';
356|alter table company_profile add column if not exists website text;
357|alter table company_profile add column if not exists currency text default 'AED';
358|alter table company_profile add column if not exists default_tax_rate numeric(8,3) default 5;
359|
360|create table if not exists invoice_docs (
361|  id bigint generated by default as identity primary key,
362|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
363|  number text not null default '',
364|  status text not null default 'draft',
365|  template text not null default 'minimal',
366|  accent text not null default '#0A0A0A',
367|  currency text not null default 'AED',
368|  seller_name text not null default '',
369|  seller_address text,
370|  seller_trn text,
371|  seller_email text,
372|  seller_phone text,
373|  logo text,
374|  customer_name text not null default '',
375|  customer_address text,
376|  customer_trn text,
377|  customer_email text,
378|  issue_date date,
379|  due_date date,
380|  notes text,
381|  terms text,
382|  tax_rate numeric(8,3) not null default 5,
383|  discount numeric(14,2) not null default 0,
384|  created_at timestamptz not null default now(),
385|  updated_at timestamptz not null default now()
386|);
387|
388|create table if not exists invoice_doc_items (
389|  id bigint generated by default as identity primary key,
390|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
391|  invoice_id bigint references invoice_docs(id) on delete cascade,
392|  product_id bigint references products(id) on delete set null,
393|  description text not null default '',
394|  qty numeric(14,3) not null default 1,
395|  unit_price numeric(14,2) not null default 0,
396|  unit text,
397|  custom jsonb,
398|  position bigint not null default 0,
397|  created_at timestamptz not null default now(),
398|  updated_at timestamptz not null default now()
399|);
400|
401|-- Payments recorded against an invoice (partial or full).
402|create table if not exists invoice_payments (
403|  id bigint generated by default as identity primary key,
404|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
405|  invoice_id bigint references invoice_docs(id) on delete cascade,
406|  amount numeric(14,2) not null default 0,
407|  method text,
408|  note text,
409|  paid_at date not null default current_date,
410|  created_at timestamptz not null default now(),
411|  updated_at timestamptz not null default now()
412|);
413|
414|-- ===== QUOTING =====
415|create table if not exists quotations (
416|  id bigint generated by default as identity primary key,
417|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
418|  number text not null default '',
419|  status text not null default 'draft',
420|  template text not null default 'clean',
421|  accent text not null default '#E0AE00',
422|  currency text not null default 'USD',
423|  quote_date date,
424|  valid_until date,
425|  sales_person text,
426|  customer_name text not null default '',
427|  customer_address text,
428|  customer_trn text,
429|  customer_email text,
430|  terms text,
431|  created_at timestamptz not null default now(),
432|  updated_at timestamptz not null default now()
433|);
434|
435|create table if not exists quotation_items (
436|  id bigint generated by default as identity primary key,
437|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
438|  quotation_id bigint references quotations(id) on delete cascade,
439|  product text not null default '',
440|  sku text,
441|  qty numeric(14,3) not null default 1,
442|  rate numeric(14,2) not null default 0,
443|  discount numeric(8,3) not null default 0,
444|  tax numeric(8,3) not null default 0,
445|  position bigint not null default 0,
446|  created_at timestamptz not null default now(),
447|  updated_at timestamptz not null default now()
448|);
449|
450|create table if not exists quotation_templates (
451|  id bigint generated by default as identity primary key,
452|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
453|  name text not null default '',
454|  base_template text not null default 'clean',
455|  created_at timestamptz not null default now(),
456|  updated_at timestamptz not null default now()
457|);
458|
459|-- ===== TOOLS activity =====
460|create table if not exists tool_runs (
461|  id bigint generated by default as identity primary key,
462|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
463|  tool text not null default '',
464|  tool_name text not null default '',
465|  file_name text not null default '',
466|  created_at timestamptz not null default now(),
467|  updated_at timestamptz not null default now()
468|);
469|-- Stored output object paths in the tool-outputs bucket (additive).
470|alter table tool_runs add column if not exists storage_paths text[] not null default '{}';
471|alter table tool_runs add column if not exists size_bytes bigint not null default 0;
472|
473|-- ---------- MULTI-TENANCY (organizations + members + RBAC) ----------
474|create extension if not exists pgcrypto;
475|
476|create table if not exists organizations (
477|  id uuid primary key default gen_random_uuid(),
478|  name text not null default 'My Organization',
479|  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
480|  created_at timestamptz not null default now(),
481|  updated_at timestamptz not null default now()
482|);
483|
484|create table if not exists org_members (
485|  id bigint generated by default as identity primary key,
486|  org_id text not null,
487|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
488|  role text not null default 'staff',
489|  created_at timestamptz not null default now(),
490|  updated_at timestamptz not null default now(),
491|  unique (org_id, user_id)
492|);
493|-- Per-member allowed module ids (null = all modules). Set by the owner.
494|alter table org_members add column if not exists modules text[];
495|
496|-- Company message board — an org-wide team feed (everyone in the org can
497|-- read; members post their own messages; authors or admins can delete).
498|create table if not exists org_messages (
499|  id bigint generated by default as identity primary key,
500|  org_id text not null default public.current_org(),
501|  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
502|  body text not null default '',
503|  created_at timestamptz not null default now(),
504|  updated_at timestamptz not null default now()
505|);
506|-- Threaded replies: a reply points at its parent message.
507|alter table org_messages add column if not exists parent_id bigint
508|  references org_messages(id) on delete cascade;
509|
510|-- Pending team invitations issued by an org owner/admin.
511|create table if not exists invitations (
512|  id uuid primary key default gen_random_uuid(),
513|  org_id text not null,
514|  email text not null,
515|  role text not null default 'staff',
516|  modules text[],
517|  invited_by uuid default auth.uid() references auth.users(id) on delete set null,
518|  status text not null default 'pending',
519|  created_at timestamptz not null default now(),
520|  updated_at timestamptz not null default now()
521|);
522|
523|-- Caller's active organization key (text). Defaults to 'default' so any
524|-- pre-existing single-user data keeps working unchanged after migration.
525|create or replace function public.current_org()
526|returns text language sql stable security definer set search_path = public as $$
527|  select coalesce(
528|    (select org_id from public.profiles where id = auth.uid()),
529|    'default'
530|  )
531|$$;
532|
533|-- SECURITY: force org_id to the caller's active org and make it immutable.
534|-- Without this, a client could INSERT a row carrying ANOTHER org's org_id
535|-- (and shared=true) — the per-member RLS check passes on the user_id branch
536|-- regardless of org_id, so the row would surface in the victim org's shared
537|-- feed (cross-tenant injection / fake-invoice phishing). On UPDATE we pin
538|-- org_id to its previous value so a row can never be moved between orgs.
539|create or replace function public.force_org_id()
540|returns trigger language plpgsql security definer set search_path = public as $$
541|begin
542|  -- Admin / service_role / SQL-migration context (no JWT) is trusted and must
543|  -- stay able to backfill org_id. Only pin org_id for real client requests.
544|  if auth.uid() is null then
545|    return new;
546|  end if;
547|  if (TG_OP = 'INSERT') then
548|    new.org_id := public.current_org();
549|  else
550|    new.org_id := old.org_id;
551|  end if;
552|  return new;
553|end $$;
554|
555|-- True when the caller is an owner/admin of their active org.
556|-- security definer avoids RLS recursion on org_members.
557|create or replace function public.is_org_admin()
558|returns boolean language sql stable security definer set search_path = public as $$
559|  select exists (
560|    select 1 from public.org_members
561|    where org_id = public.current_org()
562|      and user_id = auth.uid()
563|      and role in ('owner', 'admin')
564|  )
565|$$;
566|
567|alter table organizations enable row level security;
568|drop policy if exists organizations_access on organizations;
569|create policy organizations_access on organizations for all
570|  using (id::text = public.current_org() or owner_id = auth.uid())
571|  with check (owner_id = auth.uid());
572|drop trigger if exists trg_organizations_updated on organizations;
573|create trigger trg_organizations_updated before update on organizations
574|  for each row execute function set_updated_at();
575|
576|alter table org_members enable row level security;
577|drop policy if exists org_members_select on org_members;
578|create policy org_members_select on org_members for select
579|  using (org_id = public.current_org() or user_id = auth.uid());
580|
581|-- SECURITY: members may NOT freely insert/update their own membership —
582|-- that allowed self-escalation to owner/admin and joining arbitrary orgs.
583|drop policy if exists org_members_self on org_members;
584|
585|-- A member may leave (delete) their own membership.
586|drop policy if exists org_members_self_leave on org_members;
587|create policy org_members_self_leave on org_members for delete
588|  using (user_id = auth.uid());
589|
590|-- A user may add ONLY themselves, and ONLY to an organization they own
591|-- (covers creating a new org). Joining someone else's org is invite-only
592|-- (handled by an admin via org_members_admin).
593|drop policy if exists org_members_create_own on org_members;
594|create policy org_members_create_own on org_members for insert
595|  with check (
596|    user_id = auth.uid()
597|    and exists (
598|      select 1 from public.organizations o
599|      where o.id::text = org_members.org_id
600|        and o.owner_id = auth.uid()
601|    )
602|  );
603|
604|-- Owners/admins manage membership + roles within their active org.
605|drop policy if exists org_members_admin on org_members;
606|create policy org_members_admin on org_members for all
607|  using (org_id = public.current_org() and public.is_org_admin())
608|  with check (org_id = public.current_org() and public.is_org_admin());
609|drop trigger if exists trg_org_members_updated on org_members;
610|create trigger trg_org_members_updated before update on org_members
611|  for each row execute function set_updated_at();
612|
613|-- Team members may read each other's profiles within the same org.
614|drop policy if exists profiles_org_read on profiles;
615|create policy profiles_org_read on profiles for select
616|  using (org_id = public.current_org());
617|
618|-- ---------- invitations RLS + accept flow ----------
619|alter table invitations enable row level security;
620|drop trigger if exists trg_invitations_updated on invitations;
621|create trigger trg_invitations_updated before update on invitations
622|  for each row execute function set_updated_at();
623|
624|-- Caller's own email (security definer to read auth/profile safely).
625|create or replace function public.my_email()
626|returns text language sql stable security definer set search_path = public as $$
627|  select email from public.profiles where id = auth.uid()
628|$$;
629|
630|-- Org admins manage invitations for their active org.
631|drop policy if exists invitations_admin on invitations;
632|create policy invitations_admin on invitations for all
633|  using (org_id = public.current_org() and public.is_org_admin())
634|  with check (org_id = public.current_org() and public.is_org_admin());
635|
636|-- An invitee may read pending invitations addressed to their email.
637|drop policy if exists invitations_invitee_read on invitations;
638|create policy invitations_invitee_read on invitations for select
639|  using (lower(email) = lower(coalesce(public.my_email(), '')));
640|
641|-- Accept an invitation: validated by email match, runs as definer so it
642|-- can add the membership and switch the caller's active org safely.
643|-- ---------- notifications (per-user inbox; e.g. @mentions) ----------
644|create table if not exists notifications (
645|  id bigint generated by default as identity primary key,
646|  org_id text not null,
647|  user_id uuid not null references auth.users(id) on delete cascade, -- recipient
648|  actor text not null default '',
649|  kind text not null default 'info',
650|  body text not null default '',
651|  link text,
652|  read boolean not null default false,
653|  created_at timestamptz not null default now()
654|);
655|alter table notifications enable row level security;
656|-- A user only ever sees / mutates their own notifications. There is NO
657|-- client insert policy on purpose: rows are created only by the
658|-- security-definer mention trigger below.
659|drop policy if exists notifications_select_own on notifications;
660|create policy notifications_select_own on notifications for select
661|  using (user_id = auth.uid());
662|drop policy if exists notifications_update_own on notifications;
663|create policy notifications_update_own on notifications for update
664|  using (user_id = auth.uid()) with check (user_id = auth.uid());
665|drop policy if exists notifications_delete_own on notifications;
666|create policy notifications_delete_own on notifications for delete
667|  using (user_id = auth.uid());
668|create index if not exists idx_notifications_inbox
669|  on notifications (user_id, read, created_at desc);
670|
671|-- Fan out @mentions in a new message to the mentioned org members.
672|-- Handle = first name (lowercased), matching MentionInput's insertion.
673|create or replace function public.notify_mentions()
674|returns trigger language plpgsql security definer set search_path = public as $$
675|declare
676|  actor_name text;
677|  h text;
678|  rec record;
679|begin
680|  select coalesce(name, email, 'Someone') into actor_name
681|    from public.profiles where id = new.user_id;
682|  for h in
683|    select distinct lower(t[1])
684|    from regexp_matches(new.body, '@([A-Za-z0-9_.\-]+)', 'g') as t
685|  loop
686|    for rec in
687|      select p.id
688|      from public.profiles p
689|      join public.org_members om
690|        on om.user_id = p.id and om.org_id = new.org_id
691|      where lower(split_part(p.name, ' ', 1)) = h
692|        and p.id <> new.user_id
693|    loop
694|      insert into public.notifications (org_id, user_id, actor, kind, body, link)
695|      values (new.org_id, rec.id, actor_name, 'mention',
696|              left(new.body, 140), '/overview');
697|    end loop;
698|  end loop;
699|  return new;
700|end $$;
701|
702|drop trigger if exists trg_notify_mentions on org_messages;
703|create trigger trg_notify_mentions after insert on org_messages
704|  for each row execute function public.notify_mentions();
705|
706|-- ---------- org_messages RLS ----------
707|alter table org_messages enable row level security;
708|drop trigger if exists trg_org_messages_updated on org_messages;
709|create trigger trg_org_messages_updated before update on org_messages
710|  for each row execute function set_updated_at();
711|drop policy if exists org_messages_read on org_messages;
712|create policy org_messages_read on org_messages for select
713|  using (org_id = public.current_org());
714|drop policy if exists org_messages_insert on org_messages;
715|create policy org_messages_insert on org_messages for insert
716|  with check (user_id = auth.uid() and org_id = public.current_org());
717|drop policy if exists org_messages_modify on org_messages;
718|create policy org_messages_modify on org_messages for delete
719|  using (
720|    org_id = public.current_org()
721|    and (user_id = auth.uid() or public.is_org_admin())
722|  );
723|create index if not exists idx_org_messages_org_created
724|  on org_messages (org_id, created_at desc);
725|
726|create or replace function public.accept_invitation(invite uuid)
727|returns void language plpgsql security definer set search_path = public as $$
728|declare
729|  inv public.invitations;
730|  myemail text;
731|begin
732|  select email into myemail from public.profiles where id = auth.uid();
733|  select * into inv from public.invitations
734|    where id = invite and status = 'pending';
735|  if inv.id is null then
736|    raise exception 'Invitation not found or already used';
737|  end if;
738|  if lower(inv.email) <> lower(coalesce(myemail, '')) then
739|    raise exception 'This invitation is for a different email address';
740|  end if;
741|  insert into public.org_members (org_id, user_id, role, modules)
742|  values (inv.org_id, auth.uid(), inv.role, inv.modules)
743|  on conflict (org_id, user_id)
744|    do update set role = excluded.role, modules = excluded.modules;
745|  update public.profiles set org_id = inv.org_id where id = auth.uid();
746|  update public.invitations set status = 'accepted', updated_at = now()
747|    where id = invite;
748|end $$;
749|grant execute on function public.accept_invitation(uuid) to authenticated;
750|
751|-- ---------- RLS + org scoping + privacy model + updated_at trigger ----------
752|-- Privacy model (per the product spec):
753|--   * A member's records are PRIVATE to them by default.
754|--   * Org owners/admins can see and manage everything in the org.
755|--   * A record becomes visible to the whole org only when its owner sets
756|--     `shared = true` (opt-in, per record). Shared records are read-only
757|--     to other members (only the owner or an admin can edit them).
758|-- Org-level tables (settings, audit, company profile, legacy app_users)
759|-- stay org-scoped rather than per-member.
760|do $$
761|declare
762|  t text;
763|  tables text[] := array[
764|    'products','orders','order_items',
765|    'employees','attendance','payroll',
766|    'accounts','expenses','transactions',
767|    'app_users','app_settings','audit_log',
768|    'crm_leads','crm_customers','crm_opportunities','crm_activities',
769|    'company_profile','invoice_docs','invoice_doc_items','invoice_payments',
770|    'quotations','quotation_items','quotation_templates','tool_runs',
771|    'suppliers','purchase_orders','purchase_order_items'
772|  ];
773|  org_only text[] := array[
774|    'company_profile','app_settings','audit_log','app_users'
775|  ];
776|begin
777|  foreach t in array tables loop
778|    execute format(
779|      'alter table %I add column if not exists org_id text not null default public.current_org();',
780|      t
781|    );
782|    execute format('alter table %I enable row level security;', t);
783|    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_updated', t);
784|    execute format(
785|      'create trigger %I before update on %I for each row execute function set_updated_at();',
786|      'trg_' || t || '_updated', t
787|    );
788|
789|    -- SECURITY: pin org_id to the caller's org on insert and freeze it on
790|    -- update (prevents cross-tenant row injection — see force_org_id()).
791|    execute format('drop trigger if exists %I on %I;', 'trg_' || t || '_org', t);
792|    execute format(
793|      'create trigger %I before insert or update on %I for each row execute function public.force_org_id();',
794|      'trg_' || t || '_org', t
795|    );
796|
797|    -- clear any prior policy variants
798|    execute format('drop policy if exists %I on %I;', t || '_owner', t);
799|    execute format('drop policy if exists %I on %I;', t || '_org', t);
800|    execute format('drop policy if exists %I on %I;', t || '_access', t);
801|
802|    if t = any(org_only) then
803|      execute format(
804|        'create policy %I on %I for all using (org_id = public.current_org()) with check (org_id = public.current_org());',
805|        t || '_org', t
806|      );
807|    else
808|      execute format(
809|        'alter table %I add column if not exists shared boolean not null default false;',
810|        t
811|      );
812|      -- SECURITY: the admin / shared branches MUST be scoped to the
813|      -- caller's own org. is_org_admin() is true for an admin of *their*
814|      -- org; without the org_id match it would grant access to every
815|      -- org's rows (cross-tenant leak). Always require org_id = current_org
816|      -- on anything that isn't the caller's own row.
817|      execute format(
818|        'create policy %I on %I for all '
819|        || 'using (user_id = auth.uid() '
820|        || 'or (org_id = public.current_org() '
821|        || 'and (public.is_org_admin() or shared = true))) '
822|        || 'with check (user_id = auth.uid() '
823|        || 'or (org_id = public.current_org() and public.is_org_admin()));',
824|        t || '_access', t
825|      );
826|    end if;
827|  end loop;
828|end $$;
829|
830|-- ---------- backfill org_id from each row owner's profile ----------
831|-- When org_id was first added, the default public.current_org() ran with a
832|-- null auth.uid() (admin/SQL context) and resolved to 'default' for every
833|-- existing row. That orphans pre-migration rows in org 'default' while a
834|-- signed-in user's current_org() is their real org UUID, so RLS blocks
835|-- updates. Re-point each row to its owner's actual org. Idempotent.
836|-- NOTE: company_profile is intentionally excluded — it has a unique(org_id)
837|-- constraint and is collapsed to one row per org in its own section below.
838|-- Backfilling it here (before that dedup) can violate the constraint when
839|-- legacy duplicates exist, so leave its org_id to the dedicated block.
840|do $$
841|declare
842|  t text;
843|  tables text[] := array[
844|    'products','orders','order_items',
845|    'employees','attendance','payroll',
846|    'accounts','expenses','transactions',
847|    'app_users','app_settings','audit_log',
848|    'crm_leads','crm_customers','crm_opportunities','crm_activities',
849|    'invoice_docs','invoice_doc_items','invoice_payments',
850|    'quotations','quotation_items','quotation_templates','tool_runs',
851|    'suppliers','purchase_orders','purchase_order_items'
852|  ];
853|begin
854|  foreach t in array tables loop
855|    execute format(
856|      'update public.%I x set org_id = p.org_id
857|         from public.profiles p
858|        where x.user_id = p.id
859|          and x.org_id is distinct from p.org_id;',
860|      t
861|    );
862|  end loop;
863|end $$;
864|
865|-- ---------- company_profile: one shared profile per organization ----------
866|-- The company identity belongs to the org, not each member. Keep a single
867|-- row per org, let any member read it, but only org admins (owner/admin)
868|-- may change it — so invited members cannot rename the company.
869|do $$
870|begin
871|  -- Collapse any duplicates, keeping the earliest row per org.
872|  delete from public.company_profile a
873|   using public.company_profile b
874|   where a.org_id = b.org_id and a.id > b.id;
875|
876|  if exists (
877|    select 1 from pg_constraint where conname = 'company_profile_user_id_key'
878|  ) then
879|    alter table public.company_profile drop constraint company_profile_user_id_key;
880|  end if;
881|
882|  if not exists (
883|    select 1 from pg_constraint where conname = 'company_profile_org_id_key'
884|  ) then
885|    alter table public.company_profile
886|      add constraint company_profile_org_id_key unique (org_id);
887|  end if;
888|end $$;
889|
890|-- Read for all org members; write for org admins only.
891|drop policy if exists company_profile_org on company_profile;
892|drop policy if exists company_profile_read on company_profile;
893|drop policy if exists company_profile_write on company_profile;
894|create policy company_profile_read on company_profile for select
895|  using (org_id = public.current_org());
896|create policy company_profile_write on company_profile for all
897|  using (org_id = public.current_org() and public.is_org_admin())
898|  with check (org_id = public.current_org() and public.is_org_admin());
899|
900|-- ---------- auto-provision a personal org + profile on signup ----------
901|create or replace function handle_new_user()
902|returns trigger language plpgsql security definer set search_path = public as $$
903|declare
904|  new_org uuid;
905|begin
906|  insert into public.organizations (id, name, owner_id)
907|  values (gen_random_uuid(), coalesce(new.email, 'My Organization'), new.id)
908|  returning id into new_org;
909|
910|  insert into public.profiles (id, email, name, org_id)
911|  values (
912|    new.id,
913|    coalesce(new.email, ''),
914|    coalesce(new.raw_user_meta_data->>'full_name', 'User'),
915|    new_org::text
916|  )
917|  on conflict (id) do nothing;
918|
919|  insert into public.org_members (org_id, user_id, role)
920|  values (new_org::text, new.id, 'owner')
921|  on conflict (org_id, user_id) do nothing;
922|
923|  return new;
924|end $$;
925|
926|drop trigger if exists on_auth_user_created on auth.users;
927|create trigger on_auth_user_created
928|  after insert on auth.users
929|  for each row execute function handle_new_user();
930|
931|-- ---------- realtime: broadcast row changes for live multi-client sync ----------
932|-- Every table the app reads is added to the supabase_realtime publication
933|-- so changes from any client (desktop, web, or a direct DB edit) stream to
934|-- open sessions. RLS still filters the feed: a client only receives changes
935|-- for rows it may read. Idempotent — safe to re-run.
936|do $$
937|declare
938|  t text;
939|  rt_tables text[] := array[
940|    'products','orders','order_items',
941|    'employees','attendance','payroll',
942|    'accounts','expenses','transactions',
943|    'app_users','app_settings','audit_log',
944|    'crm_leads','crm_customers','crm_opportunities','crm_activities',
945|    'company_profile','invoice_docs','invoice_doc_items','invoice_payments',
946|    'quotations','quotation_items','quotation_templates','tool_runs',
947|    'suppliers','purchase_orders','purchase_order_items',
948|    'organizations','org_members','profiles','invitations','org_messages',
949|    'notifications'
950|  ];
951|begin
952|  if not exists (
953|    select 1 from pg_publication where pubname = 'supabase_realtime'
954|  ) then
955|    create publication supabase_realtime;
956|  end if;
957|  foreach t in array rt_tables loop
958|    if not exists (
959|      select 1 from pg_publication_tables
960|      where pubname = 'supabase_realtime'
961|        and schemaname = 'public'
962|        and tablename = t
963|    ) then
964|      execute format(
965|        'alter publication supabase_realtime add table public.%I;', t
966|      );
967|    end if;
968|  end loop;
969|end $$;
970|
971|-- ---------- referential integrity + normalization (additive) ----------
972|-- Bring legacy text-keyed fields into proper relations without breaking
973|-- any existing rows. Each constraint is added only when missing.
974|
975|-- New FK columns (safe — defaults to null for legacy rows).
976|alter table orders          add column if not exists customer_id bigint references crm_customers(id) on delete set null;
977|alter table invoice_docs    add column if not exists customer_id bigint references crm_customers(id) on delete set null;
978|alter table quotations      add column if not exists customer_id bigint references crm_customers(id) on delete set null;
979|alter table invoice_docs    add column if not exists quotation_id bigint references quotations(id) on delete set null;
980|alter table crm_opportunities add column if not exists invoice_id bigint references invoice_docs(id) on delete set null;
981|alter table crm_opportunities add column if not exists quotation_id bigint references quotations(id) on delete set null;
982|alter table invoice_doc_items add column if not exists product_id bigint references products(id) on delete set null;
983|alter table quotation_items   add column if not exists product_id bigint references products(id) on delete set null;
984|
985|-- Promote existing bigint-but-unconstrained columns to real foreign keys.
986|do $$
987|declare
988|  fkdef record;
989|begin
990|  for fkdef in
991|    select * from (values
992|      ('order_items',  'product_id', 'products', 'order_items_product_id_fkey'),
993|      ('expenses',     'account_id', 'accounts', 'expenses_account_id_fkey'),
994|      ('transactions', 'account_id', 'accounts', 'transactions_account_id_fkey')
995|    ) as v(tbl, col, ref, name)
996|  loop
997|    if not exists (select 1 from pg_constraint where conname = fkdef.name) then
998|      execute format(
999|        'alter table %I add constraint %I foreign key (%I) references %I(id) on delete set null',
1000|        fkdef.tbl, fkdef.name, fkdef.col, fkdef.ref
1001|      );
1002|    end if;
1003|  end loop;
1004|end $$;
1005|
1006|-- ---------- STORAGE: tool-outputs bucket ----------
1007|-- Private bucket holding processed tool files. Each object lives under
1008|-- {auth.uid()}/{run_id}/{i}_{name}; RLS scopes every object to its owner
1009|-- so files persist until the user deletes the run. Idempotent.
1010|insert into storage.buckets (id, name, public)
1011|values ('tool-outputs', 'tool-outputs', false)
1012|on conflict (id) do nothing;
1013|
1014|drop policy if exists tool_outputs_read on storage.objects;
1015|create policy tool_outputs_read on storage.objects for select
1016|  to authenticated
1017|  using (
1018|    bucket_id = 'tool-outputs'
1019|    and (storage.foldername(name))[1] = auth.uid()::text
1020|  );
1021|
1022|drop policy if exists tool_outputs_insert on storage.objects;
1023|create policy tool_outputs_insert on storage.objects for insert
1024|  to authenticated
1025|  with check (
1026|    bucket_id = 'tool-outputs'
1027|    and (storage.foldername(name))[1] = auth.uid()::text
1028|  );
1029|
1030|drop policy if exists tool_outputs_update on storage.objects;
1031|create policy tool_outputs_update on storage.objects for update
1032|  to authenticated
1033|  using (
1034|    bucket_id = 'tool-outputs'
1035|    and (storage.foldername(name))[1] = auth.uid()::text
1036|  )
1037|  with check (
1038|    bucket_id = 'tool-outputs'
1039|    and (storage.foldername(name))[1] = auth.uid()::text
1040|  );
1041|
1042|drop policy if exists tool_outputs_delete on storage.objects;
1043|create policy tool_outputs_delete on storage.objects for delete
1044|  to authenticated
1045|  using (
1046|    bucket_id = 'tool-outputs'
1047|    and (storage.foldername(name))[1] = auth.uid()::text
1048|  );
1049|
1050|-- ---------- RETENTION: auto-purge old tool outputs ----------
1051|-- Deletes tool_runs (and their stored files) older than max_age. Run on a
1052|-- schedule via pg_cron when available; client also enforces a per-user
1053|-- storage quota. security definer so the scheduled job may touch storage.
1054|create or replace function public.prune_tool_runs(max_age interval default '30 days')
1055|returns void language plpgsql security definer
1056|set search_path = public, storage as $$
1057|begin
1058|  delete from storage.objects o
1059|   using public.tool_runs r
1060|   where o.bucket_id = 'tool-outputs'
1061|     and o.name = any(r.storage_paths)
1062|     and r.created_at < now() - max_age;
1063|  delete from public.tool_runs where created_at < now() - max_age;
1064|end $$;
1065|
1066|do $$
1067|begin
1068|  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
1069|    create extension if not exists pg_cron;
1070|    -- pg_cron 1.4+ upserts by job name; safe to re-run.
1071|    perform cron.schedule(
1072|      'prune-tool-runs',
1073|      '0 3 * * *',
1074|      'select public.prune_tool_runs();'
1075|    );
1076|  end if;
1077|end $$;
1078|
1079|-- ---------- performance: indexes on hot columns ----------
1080|-- RLS filters on user_id/org_id/shared on every query; FKs and created_at
1081|-- are common sort/join keys. Index them so the app stays fast at scale.
1082|do $$
1083|declare
1084|  t text;
1085|  tables text[] := array[
1086|    'products','orders','order_items','employees','attendance','payroll',
1087|    'accounts','expenses','transactions','crm_leads','crm_customers',
1088|    'crm_opportunities','crm_activities','invoice_docs','invoice_doc_items','invoice_payments',
1089|    'quotations','quotation_items','quotation_templates','tool_runs',
1090|    'suppliers','purchase_orders','purchase_order_items'
1091|  ];
1092|begin
1093|  foreach t in array tables loop
1094|    execute format('create index if not exists %I on public.%I (org_id);', 'idx_'||t||'_org', t);
1095|    execute format('create index if not exists %I on public.%I (user_id);', 'idx_'||t||'_user', t);
1096|  end loop;
1097|end $$;
1098|create index if not exists idx_order_items_order on public.order_items (order_id);
1099|create index if not exists idx_invoice_doc_items_doc on public.invoice_doc_items (invoice_id);
1100|create index if not exists idx_invoice_payments_invoice on public.invoice_payments (invoice_id);
1101|create index if not exists idx_quotation_items_quote on public.quotation_items (quotation_id);
1102|create index if not exists idx_po_items_po on public.purchase_order_items (po_id);
1103|create index if not exists idx_org_members_user on public.org_members (user_id);
1104|create index if not exists idx_invitations_email on public.invitations (lower(email));
1105|create index if not exists idx_tool_runs_created on public.tool_runs (created_at);
1106|
1107|-- ---------- integrity: non-negative money/quantity checks ----------
1108|-- Added NOT VALID so they enforce new/updated rows without failing on any
1109|-- pre-existing data; validate later once data is known clean.
1110|do $$
1111|declare
1112|  c record;
1113|  checks jsonb := jsonb_build_array(
1114|    jsonb_build_object('t','products','n','chk_products_nonneg','e','unit_price >= 0 and cost_price >= 0 and quantity >= 0 and reorder_level >= 0'),
1115|    jsonb_build_object('t','orders','n','chk_orders_nonneg','e','total >= 0'),
1116|    jsonb_build_object('t','order_items','n','chk_order_items_nonneg','e','quantity >= 0 and unit_price >= 0'),
1117|    jsonb_build_object('t','invoice_docs','n','chk_invoice_docs_nonneg','e','tax_rate >= 0 and discount >= 0'),
1118|    jsonb_build_object('t','invoice_doc_items','n','chk_invoice_items_nonneg','e','qty >= 0 and unit_price >= 0'),
1119|    jsonb_build_object('t','invoice_payments','n','chk_invoice_payments_nonneg','e','amount >= 0'),
1120|    jsonb_build_object('t','quotation_items','n','chk_quote_items_nonneg','e','qty >= 0 and rate >= 0'),
1121|    jsonb_build_object('t','expenses','n','chk_expenses_nonneg','e','amount >= 0'),
1122|    jsonb_build_object('t','transactions','n','chk_txn_nonneg','e','amount >= 0'),
1123|    jsonb_build_object('t','payroll','n','chk_payroll_nonneg','e','basic >= 0 and allowances >= 0 and deductions >= 0'),
1124|    jsonb_build_object('t','purchase_order_items','n','chk_po_items_nonneg','e','quantity >= 0 and unit_cost >= 0')
1125|  );
1126|begin
1127|  for c in select * from jsonb_to_recordset(checks) as x(t text, n text, e text) loop
1128|    if not exists (select 1 from pg_constraint where conname = c.n) then
1129|      execute format('alter table public.%I add constraint %I check (%s) not valid;', c.t, c.n, c.e);
1130|    end if;
1131|  end loop;
1132|end $$;
1133|
1134|-- ---------- audit log: auto-record create/update/delete ----------
1135|-- Populates audit_log for key entities with the acting user + entity ref.
1136|-- security definer so it can write the row regardless of the caller's RLS;
1137|-- failures never block the underlying operation.
1138|create or replace function public.log_audit()
1139|returns trigger language plpgsql security definer set search_path = public as $$
1140|declare
1141|  actor_name text;
1142|  rid text;
1143|begin
1144|  begin
1145|    select coalesce(name, email, 'system') into actor_name
1146|      from public.profiles where id = auth.uid();
1147|    if (TG_OP = 'DELETE') then rid := old.id::text; else rid := new.id::text; end if;
1148|    insert into public.audit_log (actor, action, entity, details, org_id, user_id)
1149|    values (
1150|      coalesce(actor_name, 'system'),
1151|      lower(TG_OP),
1152|      TG_TABLE_NAME,
1153|      TG_TABLE_NAME || ' #' || coalesce(rid, '?'),
1154|      public.current_org(),
1155|      auth.uid()
1156|    );
1157|  exception when others then
1158|    null; -- never let auditing break the real write
1159|  end;
1160|  if (TG_OP = 'DELETE') then return old; else return new; end if;
1161|end $$;
1162|
1163|do $$
1164|declare
1165|  t text;
1166|  audited text[] := array[
1167|    'products','orders','invoice_docs','quotations','crm_customers',
1168|    'crm_leads','crm_opportunities','expenses','suppliers',
1169|    'purchase_orders','employees','payroll'
1170|  ];
1171|begin
1172|  foreach t in array audited loop
1173|    execute format('drop trigger if exists %I on public.%I;', 'trg_audit_'||t, t);
1174|    execute format(
1175|      'create trigger %I after insert or update or delete on public.%I '
1176|      || 'for each row execute function public.log_audit();',
1177|      'trg_audit_'||t, t
1178|    );
1179|  end loop;
1180|end $$;
1181|
1182|-- ---------- atomic counter updates (avoid lost-update races) ----------
1183|-- The app is realtime/multi-client, so client-side read-modify-write on a
1184|-- counter (select → compute → update) loses concurrent updates. These do the
1185|-- arithmetic in a single statement. SECURITY INVOKER (default) so RLS still
1186|-- scopes the write to rows the caller may update.
1187|create or replace function public.adjust_product_stock(p_id bigint, p_delta numeric)
1188|returns bigint language sql as $$
1189|  update public.products
1190|     set quantity = greatest(0, quantity + p_delta)
1191|   where id = p_id
1192|  returning quantity;
1193|$$;
1194|grant execute on function public.adjust_product_stock(bigint, numeric) to authenticated;
1195|
1196|create or replace function public.adjust_account_balance(p_id bigint, p_delta numeric)
1197|returns numeric language sql as $$
1198|  update public.accounts
1199|     set balance = balance + p_delta
1200|   where id = p_id
1201|  returning balance;
1202|$$;
1203|grant execute on function public.adjust_account_balance(bigint, numeric) to authenticated;
1204|
1205|-- Done. Tables are row-level-secured to the signed-in user.
1206|
1207|-- ---------- USER ASSETS (saved stamps / signatures / logos) ----------
1208|-- Personal, reusable images for the PDF tools. Per-user (not org-shared);
1209|-- the small PNG data URL is stored inline so the client can render instantly.
1210|create table if not exists user_assets (
1211|  id          uuid primary key default gen_random_uuid(),
1212|  owner       uuid not null references auth.users(id) on delete cascade,
1213|  name        text not null default 'Untitled',
1214|  ratio       real not null default 1,
1215|  data_url    text not null,
1216|  created_at  timestamptz not null default now()
1217|);
1218|create index if not exists user_assets_owner_idx on user_assets(owner, created_at desc);
1219|alter table user_assets enable row level security;
1220|drop policy if exists user_assets_self on user_assets;
1221|create policy user_assets_self on user_assets for all
1222|  using (owner = auth.uid()) with check (owner = auth.uid());
1223|
1224|-- ---------- USER FILES (saved tool outputs → "My Files") ----------
1225|-- Tool outputs the user chooses to keep. Bytes live in a private Storage
1226|-- bucket; this table holds the metadata. Per-user (owner = auth.uid()).
1227|insert into storage.buckets (id, name, public)
1228|  values ('files', 'files', false)
1229|  on conflict (id) do nothing;
1230|
1231|drop policy if exists files_own_read on storage.objects;
1232|drop policy if exists files_own_insert on storage.objects;
1233|drop policy if exists files_own_delete on storage.objects;
1234|create policy files_own_read on storage.objects for select
1235|  using (bucket_id = 'files' and (storage.foldername(name))[1] = auth.uid()::text);
1236|create policy files_own_insert on storage.objects for insert
1237|  with check (bucket_id = 'files' and (storage.foldername(name))[1] = auth.uid()::text);
1238|create policy files_own_delete on storage.objects for delete
1239|  using (bucket_id = 'files' and (storage.foldername(name))[1] = auth.uid()::text);
1240|
1241|create table if not exists user_files (
1242|  id           uuid primary key default gen_random_uuid(),
1243|  owner        uuid not null references auth.users(id) on delete cascade,
1244|  name         text not null,
1245|  mime         text not null default 'application/octet-stream',
1246|  size         bigint not null default 0,
1247|  storage_path text not null,
1248|  tool         text,
1249|  created_at   timestamptz not null default now()
1250|);
1251|create index if not exists user_files_owner_idx on user_files(owner, created_at desc);
1252|alter table user_files enable row level security;
1253|drop policy if exists user_files_self on user_files;
1254|create policy user_files_self on user_files for all
1255|  using (owner = auth.uid()) with check (owner = auth.uid());
1256|