-- Synthetic, disposable database; do not use this fixture on a customer project.
set client_min_messages=warning;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
create table auth.users(id uuid primary key);
insert into auth.users values('00000000-0000-4000-8000-000000000001'),('00000000-0000-4000-8000-000000000002'),('00000000-0000-4000-8000-000000000003');
create table org_members(org_id text,user_id uuid,role text,modules text[]);
insert into org_members values
 ('a','00000000-0000-4000-8000-000000000001','owner',null),
 ('a','00000000-0000-4000-8000-000000000002','staff',array['people','accounting']),
 ('b','00000000-0000-4000-8000-000000000003','owner',null);
create function current_org() returns text language sql stable security definer set search_path=public,pg_temp as $$ select org_id from org_members where user_id=auth.uid() $$;
create function is_org_admin() returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from org_members where user_id=auth.uid() and org_id=current_org() and role in('owner','admin')) $$;
create function filey_can_use(p_module text) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from org_members where user_id=auth.uid() and org_id=current_org() and (role in('owner','admin') or modules is null or p_module=any(modules))) $$;
create table employees(id bigint primary key,user_id uuid not null,org_id text not null,name text,shared boolean not null default false);
create table accounts(id bigint generated by default as identity primary key,user_id uuid not null default auth.uid(),org_id text not null default current_org(),code text,name text,account_type text,balance numeric(16,2) not null default 0,shared boolean not null default false);
create table payroll(id bigint generated by default as identity primary key,user_id uuid not null default auth.uid(),org_id text not null default current_org(),employee_id bigint references employees(id) on delete cascade,period text not null,basic numeric(14,2),allowances numeric(14,2),deductions numeric(14,2),net_pay numeric(14,2),status text,shared boolean not null default false);
create table transactions(id bigint generated by default as identity primary key,user_id uuid not null default auth.uid(),org_id text not null default current_org(),account_id bigint references accounts(id),txn_type text,amount numeric(16,2),description text,ref text,source text,txn_date date,shared boolean not null default false);
insert into employees values
 (1,'00000000-0000-4000-8000-000000000001','a','Owner employee',true),
 (2,'00000000-0000-4000-8000-000000000001','a','Second employee',false),
 (3,'00000000-0000-4000-8000-000000000002','a','Staff employee',true),
 (4,'00000000-0000-4000-8000-000000000003','b','Foreign employee',false),
 (5,'00000000-0000-4000-8000-000000000001','a','Delete/recreate employee',false);
-- Preserve old duplicate runs; the upgrade reserves this period once.
insert into payroll(user_id,org_id,employee_id,period,basic,allowances,deductions,net_pay,status) values
 ('00000000-0000-4000-8000-000000000001','a',1,'2026-01',10,0,0,10,'pending'),
 ('00000000-0000-4000-8000-000000000001','a',1,'2026-01',10,0,0,10,'pending'),
 ('00000000-0000-4000-8000-000000000001','a',3,'2026-01',20,0,0,20,'pending');
do $$ declare t text; begin
 foreach t in array array['employees','accounts','payroll','transactions'] loop
  execute format('alter table %I enable row level security',t);
  execute format('create policy read_rows on %I for select to authenticated using(org_id=current_org() and (user_id=auth.uid() or shared or is_org_admin()))',t);
  execute format('create policy insert_rows on %I for insert to authenticated with check(org_id=current_org() and user_id=auth.uid())',t);
  execute format('create policy update_rows on %I for update to authenticated using(org_id=current_org() and (user_id=auth.uid() or is_org_admin())) with check(org_id=current_org() and (user_id=auth.uid() or is_org_admin()))',t);
  execute format('create policy delete_rows on %I for delete to authenticated using(org_id=current_org() and (user_id=auth.uid() or is_org_admin()))',t);
 end loop;
end $$;
grant usage on schema auth,public to authenticated,anon,service_role;
grant select,insert,update,delete on employees,accounts,payroll,transactions to authenticated;
grant usage,select on all sequences in schema public to authenticated;
create function fixture_payroll_ledger_failure() returns trigger language plpgsql as $$ begin
 if new.txn_type='credit' and new.amount=777 then raise exception 'Fixture contra ledger failure'; end if;
 return new;
end $$;
create trigger fixture_payroll_ledger_failure before insert on transactions for each row execute function fixture_payroll_ledger_failure();
