-- The only successful cycle was generated by eight concurrent authenticated
-- callers using the same expected schedule date.
create temp table recurrence_assertions(label text primary key);
grant select,insert on recurrence_assertions to authenticated;
create function pg_temp.check_recurrence(p_label text,p_condition boolean) returns void language plpgsql as $$ begin
  if not coalesce(p_condition,false) then raise exception 'Recurrence assertion failed: %',p_label; end if;
  insert into recurrence_assertions values(p_label);
end $$;
do $$ declare b public.invoice_docs; d public.invoice_docs; old_fields jsonb; new_fields jsonb; old_lines jsonb; new_lines jsonb;
  today date:=(now() at time zone 'UTC')::date; next_date date:=((now() at time zone 'UTC')::date+interval '1 month')::date;
  exclusions text[]:=array['id','user_id','org_id','created_at','updated_at','sync_revision','shared','shared_with','share_token','due_date','quotation_id','order_id','number','status','issue_date','advance_applied','einvoice'];
begin
  select * into strict b from public.invoice_docs where id=920001;
  select * into strict d from public.invoice_docs where number like 'REC-'||extract(year from today)::text||'-%';
  perform pg_temp.check_recurrence('one draft per concurrent recurring cycle',d.status='draft');
  perform pg_temp.check_recurrence('stored number format honored',d.number='REC-'||extract(year from today)::text||'-0001');
  perform pg_temp.check_recurrence('source applied advance is reset',b.advance_applied=50 and d.advance_applied=0);
  perform pg_temp.check_recurrence('share token is fresh and sharing reset',d.share_token is distinct from b.share_token and not d.shared and coalesce(jsonb_array_length(d.shared_with),0)=0);
  perform pg_temp.check_recurrence('previous order and quote links cleared',d.quotation_id is null and to_jsonb(d)->>'order_id' is null);
  perform pg_temp.check_recurrence('previous payment due date cleared',d.due_date is null);
  perform pg_temp.check_recurrence('e-invoice identity refreshed',d.einvoice->>'uuid' is distinct from b.einvoice->>'uuid' and (d.einvoice->>'uuid')::uuid is not null);
  perform pg_temp.check_recurrence('e-invoice other details retained',(d.einvoice-'uuid')=(b.einvoice-'uuid'));
  perform pg_temp.check_recurrence('full business header formatting retained',(to_jsonb(d)-exclusions)=(to_jsonb(b)-exclusions));
  select jsonb_agg(to_jsonb(i)-array['id','user_id','org_id','created_at','updated_at','sync_revision','shared','shared_with','invoice_id','position'] order by position,id)
   into old_lines from public.invoice_doc_items i where invoice_id=b.id;
  select jsonb_agg(to_jsonb(i)-array['id','user_id','org_id','created_at','updated_at','sync_revision','shared','shared_with','invoice_id','position'] order by position,id)
   into new_lines from public.invoice_doc_items i where invoice_id=d.id;
  perform pg_temp.check_recurrence('all manual line fields and relative order retained',old_lines=new_lines and jsonb_array_length(new_lines)=2);
  perform pg_temp.check_recurrence('schedule and last-run committed together',exists(select 1 from public.invoice_recurrence where id=920001 and next_run=next_date and last_run=today));
  perform pg_temp.check_recurrence('one number reservation for concurrent cycle',(select count(*)=1 from public.document_number_reservations where number like 'REC-%'));
  perform pg_temp.check_recurrence('source invoice unchanged',b.advance_applied=50 and b.status='draft' and b.quotation_id=920001 and b.shared);
end $$;
set role authenticated;
set request.jwt.claim.sub='b0000000-0000-4000-8000-000000000001';
set request.jwt.claims='{"role":"authenticated","aal":"aal1"}';
select pg_temp.check_recurrence('stale completed cycle replay returns false',not public.filey_generate_recurring_invoice(920001,(now() at time zone 'UTC')::date,(now() at time zone 'UTC')::date,((now() at time zone 'UTC')::date+interval '1 month')::date,auth.uid(),public.current_org()));
select pg_temp.check_recurrence('purchase recurring cycle supported',public.filey_generate_recurring_invoice(920010,(now() at time zone 'UTC')::date,(now() at time zone 'UTC')::date,((now() at time zone 'UTC')::date+interval '1 month')::date,auth.uid(),public.current_org()));
select pg_temp.check_recurrence('purchase numbering and type honored',exists(select 1 from public.invoice_docs where number='BUY-'||extract(year from (now() at time zone 'UTC'))::text||'-0100' and doc_type='purchase' and status='draft' and advance_applied=0));
reset role;
reset request.jwt.claim.sub;
reset request.jwt.claims;
select 'PASS: '||count(*)||' real recurring invoice checks including concurrent once-only creation, field fidelity and stale-cycle replay.' from recurrence_assertions;
