set client_min_messages=warning;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
insert into auth.users values
 ('00000000-0000-0000-0000-000000000001','owner@example.invalid',now()),
 ('00000000-0000-0000-0000-000000000002','staff@example.invalid',now()),
 ('00000000-0000-0000-0000-000000000003','stranger@example.invalid',now()),
 ('00000000-0000-0000-0000-000000000004','unverified@example.invalid',null);
create table public.profiles(id uuid primary key,org_id text,email text,name text,updated_at timestamptz default now());
insert into profiles select id,case when email like 'owner%' then '10000000-0000-0000-0000-000000000001' else '10000000-0000-0000-0000-000000000002' end,email,split_part(email,'@',1),now() from auth.users;
create table public.organizations(id uuid primary key default gen_random_uuid(),name text,owner_id uuid default auth.uid(),created_at timestamptz default now());
insert into organizations values
 ('10000000-0000-0000-0000-000000000001','Team','00000000-0000-0000-0000-000000000001',now()),
 ('10000000-0000-0000-0000-000000000002','Personal','00000000-0000-0000-0000-000000000002',now());
create table public.org_members(id bigint generated by default as identity primary key,org_id text,user_id uuid default auth.uid(),role text default 'staff',modules text[],unique(org_id,user_id));
insert into org_members(org_id,user_id,role) values
 ('10000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001','owner'),
 ('10000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002','owner');
create function public.current_org() returns text language sql stable security definer set search_path=public as $$ select org_id from profiles where id=auth.uid() $$;
create function public.is_org_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from org_members where org_id=current_org() and user_id=auth.uid() and role in ('owner','admin')) $$;
create table public.invitations(id uuid primary key default gen_random_uuid(),org_id text not null,email text not null,role text default 'staff',modules text[],status text default 'pending',invited_by uuid default auth.uid(),created_at timestamptz default now(),updated_at timestamptz default now());
create table public.audit_log(id bigint generated by default as identity primary key,user_id uuid,actor text,action text,entity text,details text,created_at timestamptz default now());
create table public.org_messages(id bigint generated by default as identity primary key,org_id text default public.current_org(),user_id uuid default auth.uid(),body text,parent_id bigint references org_messages(id),channel text default 'general',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.org_channels(id bigint generated by default as identity primary key,org_id text default public.current_org(),user_id uuid default auth.uid(),name text,shared boolean default true,updated_at timestamptz default now());
create table public.notifications(id bigint generated by default as identity primary key,org_id text,user_id uuid,actor text,kind text,body text,link text,read boolean default false);
create table public.invoice_docs(id bigint primary key,user_id uuid default auth.uid(),org_id text default current_org(),shared boolean default false,shared_with jsonb default '[]',doc_type text default 'invoice',updated_at timestamptz default now(),name text);
create table public.entity_links(id bigint primary key,org_id text,user_id uuid,shared boolean default false,from_type text,to_type text,updated_at timestamptz);
create function public.notify_mentions() returns trigger language plpgsql as $$begin return new;end$$;
create trigger trg_notify_mentions after insert on org_messages for each row execute function public.notify_mentions();
alter table org_messages enable row level security;
create policy org_messages_read on org_messages for select to authenticated using(org_id=current_org());
create policy org_messages_insert on org_messages for insert to authenticated with check(org_id=current_org() and user_id=auth.uid());
create policy org_messages_delete on org_messages for delete to authenticated using(org_id=current_org() and (user_id=auth.uid() or is_org_admin()));
alter table invitations enable row level security;
alter table profiles enable row level security;
create policy profiles_read on profiles for select to authenticated using(id=auth.uid() or org_id=current_org());
create policy profiles_update on profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create publication supabase_realtime;
grant usage on schema public,auth to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
