import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { MemoryRouter } from "react-router-dom";
import { UIProvider } from "../../lib/ui";
import { billing, type CompanyProfile, type InvoiceDocSummary } from "../../lib/api";
import { loadDocFormats, pickDocNumber, type DocFormats } from "../../lib/numberFormat";
import { autoSaveDocument } from "../../lib/files";
import { savePackagingList } from "../../lib/packagingLists";
import DocumentMessageDialog from "../../components/DocumentMessageDialog";
import PackagingList from "../PackagingList";

vi.mock("../../lib/api", () => ({ getCacheScope: () => "org:user:owner", billing: { getCompany: vi.fn(async () => null), listDocs: vi.fn(async () => []), saveDoc: vi.fn() }, crm: { customers: vi.fn(async () => []) } }));
vi.mock("../../lib/agentStorage", () => ({ AGENT_STORAGE_EVENT: "filey:agent-storage", agentStorageScope: () => "local:org:user:owner", requireAgentStorageScope: () => "local:org:user:owner" }));
vi.mock("../../lib/numberFormat", () => ({ loadDocFormats: vi.fn(async () => ({})), pickDocNumber: vi.fn(() => "PL-0001") }));
vi.mock("../../lib/documentNumbers", () => ({ allocateDocumentNumber: async (...args: Parameters<typeof pickDocNumber>) => pickDocNumber(...args) }));
vi.mock("../../lib/realtime", () => ({ useLiveSync: () => {}, notifyDataChanged: () => {} }));
vi.mock("../../lib/packagingLists", async (original) => ({ ...await original<typeof import("../../lib/packagingLists")>(), loadPackagingLists: async () => [], savePackagingList: vi.fn(), deletePackagingList: vi.fn() }));
vi.mock("../../lib/files", () => ({ safeName: (name: string) => name, autoSaveDocument: vi.fn(async () => false) }));
vi.mock("../../lib/reactPdf", () => ({ reactToPdfBytes: vi.fn() }));
vi.mock("../../lib/pdfTools", () => ({ downloadFile: vi.fn() }));
vi.mock("../../components/StampSignatureSettings", () => ({ EMPTY_STAMP_SIG: {}, loadCompanyStampSig: async () => ({}) }));
vi.mock("../../components/PackagingListDocument", () => ({ default: () => <div>Document preview</div>, PACKAGING_TEMPLATES: [{ id: "packing-minimal", name: "Minimal Manifest" }], usePackagingPages: (form: { notes: string } | null) => form?.notes ? [{}, {}] : [{}] }));
vi.mock("../../components/FitPreview", () => ({ default: ({ children }: { children: React.ReactNode }) => <div>{children}</div> }));
vi.mock("../../components/DocumentMessageDialog", () => ({ default: vi.fn(() => null) }));
vi.mock("../../components/ui-menu", async (original) => ({ ...await original<typeof import("../../components/ui-menu")>(), SelectMenu: ({ value, onChange, options, ariaLabel, disabled }: { value: string; onChange: (value: string) => void; options: { value: string; label: string }[]; ariaLabel: string; disabled?: boolean }) => <select value={value} aria-label={ariaLabel} disabled={disabled} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> }));
afterEach(() => { cleanup(); vi.clearAllMocks(); });

it("distinguishes missing shipment totals from zero and shares the exact saved version", async () => {
  vi.mocked(savePackagingList).mockImplementation(async (form) => ({ id: "packing-totals", revision: 1, created_at: "2026-10-03", updated_at: "2026-10-03T12:00:00Z", form }));
  render(<MemoryRouter><UIProvider><PackagingList /></UIProvider></MemoryRouter>);
  const create = await screen.findByRole("button", { name: "New packaging list" });
  await waitFor(() => expect(create).toBeEnabled());
  await act(async () => { fireEvent.click(create); });
  fireEvent.change(screen.getByLabelText(/^Recipient name/), { target: { value: "Mary" } });
  fireEvent.mouseDown(screen.getByRole("tab", { name: "Items" }), { button: 0, ctrlKey: false });
  fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Samples" } });
  const totals = within(screen.getByRole("region", { name: "Shipment totals" }));
  expect(totals.getByText("— packages")).toBeInTheDocument();
  expect(totals.getByText("Net — kg")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: "Share" }));
  await waitFor(() => expect(DocumentMessageDialog).toHaveBeenCalled());
  const calls = vi.mocked(DocumentMessageDialog).mock.calls;
  expect(calls[calls.length - 1][0]).toEqual(expect.objectContaining({ documentVersion: "1:2026-10-03T12:00:00Z", message: expect.not.stringContaining("Packages:") }));
  await waitFor(() => expect(screen.getByLabelText("Packages")).toBeEnabled());
  fireEvent.change(screen.getByLabelText("Packages"), { target: { value: "0" } });
  expect(totals.getByText("0 packages")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: "Add item" }));
  expect(totals.getByText(/Totals include entered values/)).toBeInTheDocument();
});

it("keeps a failed standalone draft and updates the saved record by ID and revision", async () => {
  vi.mocked(savePackagingList).mockRejectedValueOnce(new Error("Storage unavailable")).mockImplementation(async (form, id, revision) => ({ id: id || "packing-1", revision: (revision || 0) + 1, created_at: "2026-10-01", updated_at: "2026-10-01", form }));
  render(<MemoryRouter><UIProvider><PackagingList /></UIProvider></MemoryRouter>);
  const create = await screen.findByRole("button", { name: "New packaging list" });
  await waitFor(() => expect(create).toBeEnabled());
  await act(async () => { fireEvent.click(create); });
  fireEvent.change(screen.getByLabelText(/^Recipient name/), { target: { value: "Independent recipient" } });
  fireEvent.mouseDown(screen.getByRole("tab", { name: "Items" }), { button: 0, ctrlKey: false });
  fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Carton of samples" } });
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await screen.findByText("Storage unavailable");
  expect(screen.getByLabelText(/^Description/)).toHaveValue("Carton of samples");
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await waitFor(() => expect(savePackagingList).toHaveBeenCalledTimes(2));
  await waitFor(() => expect(screen.getByRole("button", { name: "Save" })).toBeEnabled());
  fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Updated samples" } });
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await waitFor(() => expect(savePackagingList).toHaveBeenCalledTimes(3));
  expect(vi.mocked(savePackagingList).mock.calls[2]).toEqual([expect.objectContaining({ recipient_name: "Independent recipient", invoice_id: null, invoice_reference: "", items: [expect.objectContaining({ description: "Updated samples" })] }), "packing-1", 1, "2026-10-01"]);
  await waitFor(() => expect(autoSaveDocument).toHaveBeenLastCalledWith("PL-0001-v2-2026-10-01.pdf", "packing-list", expect.any(Function)));
  expect(billing.saveDoc).not.toHaveBeenCalled();
});

it("links an optional invoice without replacing shipment details and navigates every preview page", async () => {
  vi.mocked(billing.listDocs).mockResolvedValueOnce([{ id: 22, number: "INV-0022", customer_name: "Invoice buyer", status: "draft", template: "minimal", total: 100, updated_at: "2026-10-01" }]);
  vi.mocked(savePackagingList).mockImplementation(async (form) => ({ id: "packing-2", revision: 1, created_at: "2026-10-01", updated_at: "2026-10-01", form }));
  render(<MemoryRouter><UIProvider><PackagingList /></UIProvider></MemoryRouter>);
  const create = await screen.findByRole("button", { name: "New packaging list" });
  await waitFor(() => expect(create).toBeEnabled());
  await act(async () => { fireEvent.click(create); });
  fireEvent.change(screen.getByLabelText(/^Recipient name/), { target: { value: "Different shipment recipient" } });
  fireEvent.change(screen.getByLabelText("Notes"), { target: { value: "Continued shipment notes" } });
  fireEvent.mouseDown(screen.getByRole("tab", { name: "Items" }), { button: 0, ctrlKey: false });
  fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Independent shipment contents" } });
  fireEvent.mouseDown(screen.getByRole("tab", { name: "Details" }), { button: 0, ctrlKey: false });
  fireEvent.change(screen.getByLabelText("Optional invoice reference"), { target: { value: "22" } });
  expect(screen.getByLabelText(/^Recipient name/)).toHaveValue("Different shipment recipient");
  expect(screen.getByLabelText("Invoice reference (optional)")).toHaveValue("INV-0022");
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await waitFor(() => expect(savePackagingList).toHaveBeenCalledWith(expect.objectContaining({ invoice_id: 22, invoice_reference: "INV-0022", recipient_name: "Different shipment recipient", items: [expect.objectContaining({ description: "Independent shipment contents" })] }), undefined, undefined, undefined));
  await waitFor(() => expect(screen.getByRole("button", { name: "Preview" })).toBeEnabled());
  fireEvent.click(screen.getByRole("button", { name: "Preview" }));
  const dialog = within(screen.getByRole("dialog"));
  expect(dialog.getByText("Page 1 of 2")).toBeInTheDocument();
  fireEvent.click(dialog.getByRole("button", { name: "Next preview page" }));
  expect(dialog.getByText("Page 2 of 2")).toBeInTheDocument();
  expect(dialog.getByRole("button", { name: "Next preview page" })).toBeDisabled();
  fireEvent.click(dialog.getByRole("button", { name: "Close dialog" }));
  fireEvent.change(screen.getByLabelText("Optional invoice reference"), { target: { value: "" } });
  expect(screen.getByLabelText("Invoice reference (optional)")).toHaveValue("INV-0022");
  fireEvent.change(screen.getByLabelText("Optional invoice reference"), { target: { value: "22" } });
  fireEvent.change(screen.getByLabelText("Invoice reference (optional)"), { target: { value: "MANUAL-REF" } });
  expect(screen.getByLabelText("Optional invoice reference")).toHaveValue("");
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await waitFor(() => expect(savePackagingList).toHaveBeenLastCalledWith(expect.objectContaining({ invoice_id: null, invoice_reference: "MANUAL-REF", recipient_name: "Different shipment recipient", items: [expect.objectContaining({ description: "Independent shipment contents" })] }), "packing-2", 1, "2026-10-01"));
  expect(billing.saveDoc).not.toHaveBeenCalled();
});

it("duplicates item details with a fresh identity and saves the chosen item order", async () => {
  vi.mocked(savePackagingList).mockImplementation(async (form) => ({ id: "packing-3", revision: 1, created_at: "2026-10-01", updated_at: "2026-10-01", form }));
  render(<MemoryRouter><UIProvider><PackagingList /></UIProvider></MemoryRouter>);
  const create = await screen.findByRole("button", { name: "New packaging list" });
  await waitFor(() => expect(create).toBeEnabled());
  await act(async () => { fireEvent.click(create); });
  fireEvent.change(screen.getByLabelText(/^Recipient name/), { target: { value: "Shipment recipient" } });
  fireEvent.mouseDown(screen.getByRole("tab", { name: "Items" }), { button: 0, ctrlKey: false });
  fireEvent.change(screen.getByLabelText(/^Description/), { target: { value: "Original contents" } });
  fireEvent.change(screen.getByLabelText("Quantity"), { target: { value: "3" } });
  fireEvent.change(screen.getByLabelText("Packages"), { target: { value: "2" } });
  fireEvent.change(screen.getByLabelText("Net / unit (kg)"), { target: { value: "3.5" } });
  fireEvent.change(screen.getByLabelText("Gross / unit (kg)"), { target: { value: "4" } });
  expect(screen.getByRole("button", { name: "Move item 1 up" })).toBeDisabled();
  expect(screen.getByRole("button", { name: "Move item 1 down" })).toBeDisabled();
  fireEvent.click(screen.getByRole("button", { name: "Duplicate item 1" }));
  const copied = within(screen.getByRole("region", { name: "Item 2" }));
  expect(copied.getByLabelText("Quantity")).toHaveValue(3);
  expect(copied.getByLabelText("Packages")).toHaveValue(2);
  expect(copied.getByLabelText("Net / unit (kg)")).toHaveValue(3.5);
  expect(copied.getByLabelText("Gross / unit (kg)")).toHaveValue(4);
  fireEvent.change(copied.getByLabelText(/^Description/), { target: { value: "Copied contents" } });
  fireEvent.click(screen.getByRole("button", { name: "Move item 2 up" }));
  expect(screen.getAllByLabelText(/^Description/).map((input) => (input as HTMLTextAreaElement).value)).toEqual(["Copied contents", "Original contents"]);
  fireEvent.click(screen.getByRole("button", { name: "Move item 1 down" }));
  expect(screen.getAllByLabelText(/^Description/).map((input) => (input as HTMLTextAreaElement).value)).toEqual(["Original contents", "Copied contents"]);
  fireEvent.click(screen.getByRole("button", { name: "Move item 2 up" }));
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await waitFor(() => expect(savePackagingList).toHaveBeenCalledTimes(1));
  const saved = vi.mocked(savePackagingList).mock.calls[0][0].items;
  expect(saved.map((item) => item.description)).toEqual(["Copied contents", "Original contents"]);
  expect(new Set(saved.map((item) => item.id)).size).toBe(2);
  expect(saved.every((item) => item.qty === 3 && item.package_count === 2 && item.net_weight === 3.5 && item.gross_weight === 4)).toBe(true);
});

it("waits for company and numbering defaults while keeping pending optional lookups independent", async () => {
  let resolveCompany!: (company: CompanyProfile) => void;
  let resolveFormats!: (formats: DocFormats) => void;
  let resolveInvoices!: (invoices: InvoiceDocSummary[]) => void;
  vi.mocked(billing.getCompany).mockReturnValueOnce(new Promise((resolve) => { resolveCompany = resolve; }));
  vi.mocked(loadDocFormats).mockReturnValueOnce(new Promise((resolve) => { resolveFormats = resolve; }));
  vi.mocked(billing.listDocs).mockReturnValueOnce(new Promise((resolve) => { resolveInvoices = resolve; }));
  render(<MemoryRouter><UIProvider><PackagingList /></UIProvider></MemoryRouter>);
  const create = await screen.findByRole("button", { name: "New packaging list" });
  expect(create).toBeDisabled();
  resolveCompany({ name: "Saved company", default_accent: "#222222", default_template: "minimal" });
  await waitFor(() => expect(billing.getCompany).toHaveBeenCalled());
  expect(create).toBeDisabled();
  resolveFormats({ packaging_list: "SHIP-{001}" });
  await waitFor(() => expect(create).toBeEnabled());
  await act(async () => { fireEvent.click(create); });
  expect(screen.getByLabelText("Company name")).toHaveValue("Saved company");
  expect(pickDocNumber).toHaveBeenCalledWith("packaging_list", [], { packaging_list: "SHIP-{001}" });
  expect(screen.getByLabelText("Optional invoice reference")).toBeDisabled();
  expect(screen.getByLabelText(/^Recipient name/)).toBeEnabled();
  fireEvent.change(screen.getByLabelText(/^Recipient name/), { target: { value: "Manual recipient" } });
  resolveInvoices([]);
  await waitFor(() => expect(screen.getByLabelText("Optional invoice reference")).toBeEnabled());
  expect(screen.getByLabelText(/^Recipient name/)).toHaveValue("Manual recipient");
});
