// One-off: convert audit workflow JSON output to AUDIT-2026-06-12.md
import fs from "fs";

const src =
  "C:/Users/iamvi/AppData/Local/Temp/claude/C--Users-iamvi-Documents-GitHub-Filey-erp/4abc6f6b-de24-4f6f-9d0f-63606c09f0ff/tasks/wo6rtzdom.output";
const data = JSON.parse(fs.readFileSync(src, "utf8"));
const raw = data.result.raw;

let md =
  "# Filey ERP — Full Audit Findings (2026-06-12)\n\n" +
  "Generated by 17 parallel audit agents over " +
  raw.length +
  " files. Theme-level loud styling already fixed centrally (tokens/ui.tsx/index.css) — entries below list remaining production gaps and dead ends.\n\n";

for (const f of raw) {
  const file = f.file.replace(/^.*Filey-erp[\\/]/, "").replaceAll("\\", "/");
  md += "## " + file + "\n\n" + (f.summary || "") + "\n\n";
  if ((f.productionGaps || []).length) {
    md += "### Production gaps\n";
    for (const g of f.productionGaps) md += "- " + g + "\n";
    md += "\n";
  }
  if ((f.stubsOrDeadEnds || []).length) {
    md += "### Stubs / dead ends\n";
    for (const s of f.stubsOrDeadEnds) md += "- " + s + "\n";
    md += "\n";
  }
}
fs.writeFileSync("AUDIT-2026-06-12.md", md);
console.log("files:", raw.length, "bytes:", md.length);
const counts = raw
  .map((f) => [
    f.file.replace(/^.*[\\/](pages|components)[\\/]/, "$1/"),
    (f.productionGaps || []).length,
  ])
  .sort((a, b) => b[1] - a[1]);
for (const c of counts) console.log(c[1] + "  " + c[0]);
